### ISSUE TITLE
Make max_member syntax consistent with max

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#101]
Hello

The max_member syntax is different from max and is not using the scope parameter. Pls find an example in the stressed VaR notebook available on this link: https://github.com/atoti/notebooks/blob/master/finance/stressed-var-calibration/main.ipynb

As is: I have to set Historical Dates to non-slicing and use the following syntax for the `max_member` which is different from `max`. The `max` calculation does not require the Historical Dates to be non-slicing:

```
# This measure is computing the worst VaR value:
m["Worst VaR"] = tt.agg.max(
    m["1d 99% VaR Sliding"], scope=tt.scope.origin(l["Historical Dates"])
)

# This measure is computing the worst VaR window (identified by the end date):
m["Worst VaR Period End"] = tt.agg.max_member(
    m["1d 99% VaR Sliding"], l["Historical Dates"]
)
```

Proposed to be: allow computing `max_member` for slicing hierarchies (as it works for `max`), and make the syntax consistent with `max` function:

```

# This measure is computing the worst VaR window (identified by the end date):
m["Worst VaR Period End"] = tt.agg.max_member(
    m["1d 99% VaR Sliding"], scope=tt.scope.origin(l["Historical Dates"])
)
```

**Comment by Skyscimitar** [comment]
I'm not sure I understand the first part of the issue.  
`tt.agg.max` does not aggregate over a slicing hierarchy.

For example:
```python
import pandas as pd
import atoti as tt

cols = ["A", "C", "B"]
rows = [
    ["a", "a", 1.],
    ["a", "c", 3.],
    ["b", "b", 2.],
    ["c", "c", 3.],
    ["d", "d", 4.]
]
df = pd.DataFrame(rows, columns=cols)

session = tt.create_session()
store = session.read_pandas(df, store_name="Store")
cube = session.create_cube(store)

h, l, m = cube.hierarchies, cube.levels, cube.measures
h["A"].slicing = True

m["max"] = tt.agg.max(m["B.SUM"], scope=tt.scope.origin(l["A"], l["C"]))
m["max_memberA"] = tt.agg.max_member(m["B.SUM"], l["A"])
m["max_memberC"] = tt.agg.max_member(m["B.SUM"], l["C"])
```
If we query `m["max"]` at the top level, the returned value will be 3, since the default comparator on the slicing hierarchy is the natural order comparator, the default member is `a` and so we get the max of `B` where `A=a`. Which is not the max of `B` accross all the values.

![Screenshot(68)](https://user-images.githubusercontent.com/24211435/88034608-31616280-cb41-11ea-8efc-4a420842865a.png)


If we set slicing to `False` the values will then be aggregated across all the members of the previously slicing hierarchy, and the top level value of `m["max"]` will be 4.

![Screenshot(69)](https://user-images.githubusercontent.com/24211435/88034713-5eae1080-cb41-11ea-9778-a68eaf4a7509.png)

The `max_member` function follows the same behavior, always returning the value of the member for which the max is reached.

For the API I will rework it so it is consistent with the rest of the API.

**Comment by APolyakova** [comment]
Hi @Skyscimitar 
This is good to know.
So if I want to compute over a slicing hierarchy, how can I do that? I thought setting scope to the members of that hierarchy will make the max to loop through them and find the max. But from your example, I see that in case of slicing, it will only look at the default member.

Example use case: AsOfDate is often a slicing hiearchy in finance. I want a post-processor that will compute max daily PL for the current year.

**Comment by Skyscimitar** [comment]
A slicing hierarchy does not have an `ALL` top level. Therefore aggregating above it does not do anything. If you want to aggregate over a slicing hierarchy, it should not be slicing. The `scope.origin` is useful when computing the aggregation of all the children of a member on a level.

**Comment by APolyakova** [comment]
Thank you @Skyscimitar I'm a bit confused, let me involve @robbiemouat as we worked together on a similar use case.

@robbiemouat could you kindly explain how do we compute cumulative PL over historical dates, or number of exceptions? Daniel explained why aggregation across slicing hierarchy is not possible.

**Comment by bloussou** [comment]
Hello,
Can we close this as there is not update ? Or is this still something you have issue with ?
Best

**Comment by bloussou** [comment]
I'm closing this as there are no updates
