### ISSUE TITLE
Ability to tweak cell's state to manipulate chart or pivot table under notebook

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#104]
## Description

We have been asked a couple of times on how to tweak cell's state to manipulate chart.
It would be nice to provide documentation on how to tweak the notebook's cell state.

atoti's charts are built on top of plotly. Hence, much of it can be configured from the property inspector with reference to the plotly script reference:

e.g. to change the fonts (https://plotly.com/javascript/reference/#layout-font), we add the below under the "configuration" (refer to attached gif
):
```
                        "plotly": {
                            "layout": {
                                "font": {
                                    "family": "Courier New",
                                    "size": "16",
                                    "color": "blue"
                                }
                            }
                        },
```
![plotly_configuration](https://user-images.githubusercontent.com/35210495/87530632-2df25500-c6c3-11ea-9829-e8c77e3a722e.gif)

If you would like to override the lines settings, you can do so by adding the below under configuration using "commonTraceOverride" if you want it to override for all traces (reference https://plotly.com/javascript/reference/#scatter-marker-line for the configurable options under data):
```
                        "plotly": {
                            "data": {
                                "commonTraceOverride": {
                                    "hoverinfo": "x+y",
                                    "line": {
                                        "shape": "hvh",
                                        "width": "5"
                                    },
                                    "mode": "lines"
                                }
                            }
                        }
```
![image (2)](https://user-images.githubusercontent.com/35210495/87530654-334f9f80-c6c3-11ea-85a7-5c0e8cacd92a.png)

Alternatively, you can overwrite by index or by tracekey. Refer to attached powerpoint for more details.
[atoti-chart-plotly-configuration.pptx](https://github.com/atoti/atoti/files/4924343/atoti-chart-plotly-configuration.pptx)

**Comment by tibdex** [comment]
In the next release, there will be a new context menu action on widgets to open the state editor so I'll close this but keep #105 open.

**Comment by mattange** [comment]
hi All

thanks for the excellent product. I have  a question with regards to the topic of this Issue,
I have been looking into the state editor for 0.7.2 and i cannot see the same original cell state as in the pictures above. Where (if anywhere) can this customisation be applied to? i.e. it appears that the cell state has changed since this issue was opened and the guide here seems not applicable anymore?
* is there an equivalent functionality now?
* For example, how do i just change the colours of a waterfall chart made via Plotly? i see defaults being green up and red down but i can't find a way to modify those in Atoti (although i know they can be modified in Plotly!)
*
