### ISSUE TITLE
Query bookmarks directly in Atoti

### ISSUE THREAD

**Issue by mingkongwoo** [atoti/atoti#106]
## Description

Would it be possible in future to query bookmark from the QuerySession from bookmark id or name?

## Context

Users may want to access bookmarks in pre-existing ActivePivot solution.

**Comment by fabiencelier** [comment]
Hello,
It's not clear to me what you mean by "query bookmark" and why you want to do it in a notebook.
I might be wrong but to me a bookmark is a full dashboard and atoti does not support building dashboards in the notebook.
If you are talking about saved widgets then I don't see what it brings to visualize it in the notebook rather than the ActiveUI application.

The only benefits I see of retrieving something to the notebook from an existing cube is to do further analysis. For that you need to retrieve the data as pandas dataframe (or similar) not as an ActiveUI widget.

So the only interesting thing we could do is to convert an existing saved pivot table to a pandas dataframe, which can already be done by copying the MDX and using [query_mdx](https://docs.atoti.io/0.4.1/lib/atoti.query.html#atoti.query.session.QuerySession.query_mdx)

**Comment by mingkongwoo** [comment]
Sorry if the context was not very clear.
For example given an existing ActivePivot solution such as FRTB, if user wants to extract some the results of a dashboard as a set of dataframes, for reporting purpose (in excel). This could be for example, necessary for regulatory reporting where the reports are submitted to regulators in Excel files.
Currently, user would have to "know" the MDX used in the dashboard and retrieve the pivot tables as dataframes using `query_mdx` as you pointed. 
However, it would be convenient for user if he could query by the bookmark directly, and not having to first find out the MDX query for each pivot table.
Also, all the dataframes corresponding to the pivot tables in a dashboard, can be returned in a single call, which is more efficient.

**Comment by tibdex** [comment]
> Also, all the dataframes corresponding to the pivot tables in a dashboard, can be returned in a single call, which is more efficient.

I don't get this part. Why would a "single call" be enough?

---

For the rest, we don't plan to add this feature but you could do it this way:

1. Use Python to make a request on the Content Server API to retrieve the content of your saved widget/dashboard from its ID (you can look at how the app does it by looking at the network tab of your browser).
2. Parse the resulting JSON response and extract the MDX from it
3. Use `session.query_mdx()` to execute the corresponding request.
