### ISSUE TITLE
Quantile does not work for indexed measure

### ISSUE THREAD

**Issue by mingkongwoo** [atoti/atoti#117]
I have a vector measure of size 10.
`m['Exposure.SUM'] =  tt.agg.sum(data_store["Exposure"])`
and an indexed measure based on the vector measure,.
`m['Exposure Detail'] = m['Exposure.SUM'][m["Simulation Index"]]`

I want to compute the 95% quantile across all the elements in the vector.
I used `atoti.agg.quantile` as documented in [documentation](https://docs.atoti.io/0.4.2/lib/atoti.html?highlight=quantile#atoti.agg.quantile).
Example: `m['pct 0.95'] = tt.agg.quantile(m['Exposure Detail'], 0.95, mode="inc", interpolation="linear", scope=tt.scope.origin(lvl["Simulation"]))`
But result is not expected.
I'm not sure if it's something wrong with the usage of `quantile` or is there a bug?

## Steps to reproduce
See attached example.
[quantile.zip](https://github.com/atoti/atoti/files/4958377/quantile.zip)

## Actual Result
For the BizDate 2020-01-01, the values of `m["Exposure Detail"]` are 100.0, 101.0, ..., 109.0.
But the value for `m["pct 0.95"]` is 100.0.

## Expected Result
I was expecting 108.50.

## Environment

- atoti: 0.4.2
- Python: 3.7
- Operating System: Windows

**Comment by fabiencelier** [comment]
Hello,

Thank you for reporting this bug

There is an issue with the vector aggregation (used by tt.agg.quantile) and the analysis hierarchy. This can be reproduced like that:

```python
m["test"] = [10,20,30,40,50,60,70,80,90,100]
cube.create_parameter_hierarchy("param", [0,1,2,3,4,5,6,7,9])
m["param"] = l["param"]

m["value"] = m["test"][m["param"]]
cube.query(m["value"], levels=l["param"])
```

| param | value |
|-------|-------|
|    0  |    10 |
|    1  |    20 |
|    2  |    30 |
|    3  |    40 |
|    4  |    50 |
|    5  |    60 |
|    6  |    70 |
|    7  |    80 |
|    9  |   100 |



The array is correctly exploded but not correctly re aggregated:

```python
m["vec"] = tt.agg._vector(m["value"], scope=tt.scope.origin(l["param"]))
cube.query(m["test"],  m["vec"])
```

|    |                   test                     | vec  |
|----|--------------------------------------------|------|
| 0  | [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  | [10] |

**Comment by fabiencelier** [comment]
Oh wait, this is not a bug, this is because the parameter hierarchy is slicing so you only see one member at a time. If you want to aggregate over all the member of the parameter hierarchy you must make it not slicing.

Following my previous example:

```python
h["param"].slicing = False
cube.query(m["test"],  m["vec"])
```

|                   test                     |                    vec                    |
|--------------------------------------------|-------------------------------------------|
| [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]  | [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] |

So we can then take the tt.array.quantile of this vector, which is equivalent to using tt.agg.quantile

```python
m["q1"] = tt.array.quantile(m["vec"], 0.95, mode="inc", interpolation="linear")
m["q2"] = tt.agg.quantile(
    m["value"], 0.95,  mode="inc", interpolation="linear", scope=tt.scope.origin(l["param"])
)
cube.query(m["q1"], m["q2"])
```
| ​q1  | q2 |
|------|----|
|  95  | 95 |

In you code calling `h["Simulation"].slicing = False` gives the expected 108.5 result for the quantile !

**Comment by mingkongwoo** [comment]
Thanks. it works now!
