### ISSUE TITLE
Year to Date window

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#119]
## Description
In the cumulative scope you can pass a window and choose how many days/month/ year you want to accumulate on a date level. Those values are discrete, in finance there is the year to date window that consist of taking all the dates since a specific date. Most of the time this date is 1st January but it could be another date.
Therefore, if you have dates going from 2018-02-12 to 2020-05-20 if you choose 2020-01-01 as first date, you would only accumulate 2020-01-01 -> 2020-05-20.
And if you choose 2019-11-01 as first date you would accumulate 2019-11-01 -> 2020-01-01.

## Context
It is one request for the simcorp poc where they have cumulative measure over different range of time (1 day, 1 month, 3 month, 1 year, all dates and year to date).

**Comment by fabiencelier** [comment]
Hello

With a multi level date hierarchy you can put a use set a partitioning level in the cumulative scope, and the aggregation will happen by partition only.

For instance with a Year / Month / Day (where day is in fact the date) you can do something like this to get the value from the beginning of the year to the current date or from the beginning of the month to the current date:

```python
# partitioning by year means resetting the aggregation at the beginning of each year.
m["year-to-date"] = tt.agg.sum(
    m["value.SUM"],
    scope=tt.scope.cumulative(lvl["Day"], partitioning=lvl["Year"])
)
m["month-to-date"] = tt.agg.sum(
    m["value.SUM"],
    scope=tt.scope.cumulative(lvl["Day"], partitioning=lvl["Month"])
)
```
So for my constant measure it gives result like that:
![newplot](https://user-images.githubusercontent.com/17087544/89173901-3ed90c80-d585-11ea-951e-0feb416097b7.png)

Then it depends how you want to "choose" the first date (current date in the coordinates, filter, analysis hierarchy, fixed in Python...) but this feature combined with filters and custom cumulative range must be enough to do what you want
