### ISSUE TITLE
Gauge chart going out of alignment when content editor is expanded

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#13]
## Description

The value in gauge chart went out of alignment when the content editor is expanded.

![image](https://user-images.githubusercontent.com/35210495/78628255-3407b700-78c6-11ea-815c-5edd7d97d5a9.png)

- Atoti version: 0.3.0.20200403103345
- Browser: Chrome
- Operating System: Windows 10 Pro

**Comment by rcolle** [comment]
Thanks for reporting!
@tibdex  this looks like a core ActiveUI issue. What do you think?

**Comment by tibdex** [comment]
Hi Hui Fang, I can reproduce this but I can always manage to get it aligned again by resizing some more:

![Apr-15-2020 15-01-08](https://user-images.githubusercontent.com/6574550/79340176-3a330e80-7f2a-11ea-90d1-5c9287df4b48.gif)

It doesn't happen in ActiveUI. Maybe it's because the codebases of JupyterLab and ActiveUI combined register too many resize event listeners for the browser to keep being responsive.

There isn't much we can do on our side to fix this.
