### ISSUE TITLE
Unable to select fields for drillthrough in view mode

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#131]
## Steps to reproduce
In viewing mode, I tried to do a drillthrough. However, it displays the last selected fields of drillthrough which was done in Editing mode and I have no ways of changing these fields. 
![image](https://user-images.githubusercontent.com/35210495/90489119-72b05680-e16f-11ea-82c7-c1d335257ef7.png)

In this case, there can only be 1 predefined view of drillthrough for all the dashboards in viewing mode.

## Environment
- atoti: 0.4.2
- Operating System: win32

**Comment by tibdex** [comment]
Hi HuiFang, the view mode is made for when your dashboards are fully built and ready to be shared with less technical users. Why don't you go back in edit mode to add more columns?

**Comment by HuifangYeo** [comment]
Hi @tibdex,
even if I predefined, it meant one configuration for all dashboards isn't it?
Or can I define a set of drillthrough columns per dashboard?

**Comment by tibdex** [comment]
I think the idea of the view mode is to stop modifying the structure of the dashboard and just browse what's already there with minimal distractions, potentially changing the filters a bit but not going much further in the analysis. That's why I'm saying that you could go back to edit mode to create all your drillthroughs with the columns you want, save your dashboard and then switch back to view mode and it will keep showing the columns you picked before.
