### ISSUE TITLE
Slow query on large dataset

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#146]
## Steps to reproduce

Download `2019-Oct.csv` file (5.28GB - 42.448.764 rows) from https://www.kaggle.com/mkechinov/ecommerce-behavior-data-from-multi-category-store

Then run the following lines:
```python
import atoti

session = atoti.create_session()
october_store = session.read_csv('2019-Oct.csv')
cube = session.create_cube(october_store)
session.load_all_data()

# CPU times: user 29.3 s, sys: 2.14 s, total: 31.5 s
# Wall time: 1min 10s
cube.query(m['price.MEAN'], levels=[lvl['user_id']])
```

## Actual Result

It takes 1 minute and 10 seconds for atoti to compute the result. I observe similar timing with `contributors.COUNT` as well.

![image](https://user-images.githubusercontent.com/4415696/92036678-e73ee400-ed70-11ea-8e81-17cabb4d30fb.png)

In comparison, with pandas it takes less than 3 seconds...

```python
import pandas as pd

october_df = pd.read_csv('2019-Oct.csv')

# CPU times: user 2.88 s, sys: 47.3 ms, total: 2.92 s
# Wall time: 2.93 s
october_df.groupby('user_id').agg({'price': 'mean'})
```

![image](https://user-images.githubusercontent.com/4415696/92035195-a514a300-ed6e-11ea-9be5-8bd271855cdc.png)

## Expected Result

I would expect timings to be similar if not faster than pandas. We can observe in the above timing that almost 30 seconds is spent in Python (probably transferring data from JAVA to Python and populating the data frame) while 40 seconds is spent in JAVA computing the query. That alone is still more than 13 times slower.

Anyway we can improve such timing?

Note that I haven't changed the `max_memory` parameter and/or set any JAVA flags as I think most of our users would not tweak those parameters. If some of those improve timings or fix the issue please document them. 

## Environment

- atoti: 0.4.4.20200901144640
- Python: 3.8.5
- Operating System: linux
- CPU:  Intel(R) Xeon(R) CPU E3-1505M v6 @ 3.00GHz; 4 cores, 8 threads
- RAM: 32GB

**Comment by fabiencelier** [comment]
These slow queries are because your query results are big. atoti can handle very large input files but it is not optimized for large output.

In comparaison if you aggregate the same data on levels with smaller cardinality you end up with query faster than pandas:

```python
#atoti
%%time
cube.query(m['price.MEAN'], levels=[lvl['brand']])

CPU times: user 38.9 ms, sys: 4.31 ms, total: 43.2 ms
Wall time: 530 ms
```
```python
#pandas
%%time
october_df.groupby('brand').agg({'price': 'mean'})

CPU times: user 2.18 s, sys: 27.9 ms, total: 2.21 s
Wall time: 2.21 s
```

For your big result query most of the time is spent serializing into JSON and deserializing the JSON in Python, then creating the pandas dataframe.

You can see how long the Java process takes to compute the result by using [explain_query](https://docs.atoti.io/0.4.3/lib/atoti.html?highlight=explain_query#atoti.cube.Cube.explain_query):

```python
cube.explain_query(m['price.MEAN'], levels=[lvl['user_id']])
```

![image](https://user-images.githubusercontent.com/17087544/92099615-05412e80-eddb-11ea-984f-3485001ad457.png)

You can see that I have a query execution time of 1.4s meaning that almost a full minute is spent in data transfers.

_Side note: you can slightly improve the timings of the query by adding keys to your store and partitioning on the `user_id` field but you'll still have the same data transfer timings._

**Comment by jbe456** [comment]
>For your big result query most of the time is spent serializing into JSON and deserializing the JSON in Python, then creating the pandas dataframe.

Thanks. Is there any plan to improve it?

> Side note: you can slightly improve the timings of the query by adding keys to your store and partitioning on the user_id field but you'll still have the same data transfer timings.

From the documentation:

> Base stores are automatically partitioned by hashing their key fields. If there are no key fields, all the dictionarized fields are hashed.

so can you explain why does it matter to add `user_id` as a key field? `user_id` is inferred as a type `int`: does it mean it won't be dictionarized? would I need to do the same trick if the requested field was of type `string`?

**Comment by tibdex** [comment]
A new `mode="raw"` option will be available on `cube.query()` in the next release to speed things up.
