### ISSUE TITLE
argument type mismatch in the parent_value function (dev: 0.4.4.2...) 

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#158]
The line began giving an exception in the [Value-at-Risk ](https://github.com/atoti/notebooks/tree/master/finance/value-at-risk) notebook when run with the latest version of atoti (dev):

```m["Parent VaR"] = atoti.parent_value(m["VaR"], h["Trading Book Hierarchy"])```

Exception:

```
AtotiJavaException: argument type mismatch
```

Version: 0.4.4.20200924141013

**Comment by bloussou** [comment]
We are now doing breaking changes on `atoti.parent_value` in order to support multiple hierarchies. So now you have to give a mapping `{Hierarchy: degree}`. `m["Parent VaR"] = atoti.parent_value(m["VaR"], {h["Trading Book Hierarchy"]: 1})` works. It will may be change again before the next release.

If you are working in jupyter lab you can access the current doc with `shift+tab`, it may help in such situation.

**Comment by APolyakova** [comment]
Thank you @bloussou

**Comment by jbe456** [comment]
could you explain what "degree" is in that context?

**Comment by rcolle** [comment]
Hi @jbe456 ,
Can you tell from the doc or does it a better explanation?
https://activeviam.jfrog.io/artifactory/atoti-generic-continuous/0.4.4.20201009150246/atoti-docs-0.4.4.20201009150246.zip!/lib/atoti.html?highlight=parent_value#atoti.parent_value

**Comment by jbe456** [comment]
I understand "degree" as a "level shift" across a multilevel hierarchy. I think your documentation sentence explains it correctly.. And I can see it's optional as well. That seems good enough.
