### ISSUE TITLE
Python UDF ala pyspark

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#161]
## Description

Not a feature request as I don't have a specific use case in mind. More a general question since the topic comes up regularly when showing atoti: have you tried/considered offering python UDF (User Defined Function) in atoti the same way it's possible to [implement UDF in pyspark](https://stackoverflow.com/questions/53477475/how-does-udf-user-defined-function-work-in-pyspark)?

>UDF can be given to PySpark in 2 ways.
>
>  1. UDF can be defined in Scala and run using PySpark
>  1. UDF can be defined in Python and run by PySpark
>
>In first case UDF will run as part of Executor JVM itself, since UDF itself is defined in Scala. There is no need to create python process.
>
>In second case for each executor a python process will be started. data will be serialised and deserialised between executor and python to process. This leads to lots of performance impact and overhead on spark job.
>
>usually it is preferred to use Scala based UDF, since they will give you better performance.
>
>in spark 2.x There is something called Pandas Udf(vectorised UDF). They are implemented using Pandas(Converting Dataframe using apache arrow). Basically you write code in python but that code is converted and run using pandas. which drastically improves performance of UDF in python.

Correlated to that question: why would spark continues offering UDF if it is [way slower than spark functions](https://stackoverflow.com/questions/38296609/spark-functions-vs-udf-performance)? It sounds like it's a popular feature on the paper that would be in practice never used anyway.

One advantage I see for UDF is that it would unlock great possibilities in atoti since the whole Python world would become available/callable from atoti. But in practice it would not work for many use cases because of performance reasons and it could be an incentive to not improve the atoti API (users implementing things in Python rather than opening a ticket for it).

Just thought it would be good to have an official public answer on this topic in case anyone searches for it.

**Comment by rcolle** [comment]
Hi Julien,

We decided not to offer Python UDF for a few reasons:

- We'll have the same problem as `Spark`, namely that the performance of such functions would be very poor because of the need to serialize data between the JVM and Python processes. `atoti` provides fast queries on top of large volumes of data, and can be easily deployed as a production system. Using Python UDFs would defeat that purpose and force the `atoti` programs to be rewritten before they can be actually used in production.
- UDFs are only part of the story with `atoti`. Contrary to Spark, we are a multidimensional system that allows queries to "navigate" in the cube. UDFs only provide "basic" transformations. Therefore the user will also need to use a lot our API (`at`, `date_shift`, `parent_value`, ...) for these operations. And then there are also the aggregation functions (which can also be defined in `Spark` using UDAFs, so that's another API to learn).

We're not completely ruling out proposing Python UDFs one day, There's actually an open internship position to evaluate some techniques that we believe we could use to mitigate the performance drawbacks. But it's definitely not a top priority development since all "real" `atoti` applications used in production use the native `atoti` API to achieve top-grade performance.

**Comment by jbe456** [comment]
Thanks for the official answer!
