### ISSUE TITLE
Being able to use the Export PDF function from Jupyter Lab: cube.visualize() not showing the chart

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#162]
## Steps to reproduce

In Jupyter Lab, using menu File > Export Notebook As.. > Export Notebook to PDF
Installed all the components requested here: https://nbconvert.readthedocs.io/en/latest/install.html

## Actual Result

No display of the chart for cube.visualize()
![image](https://user-images.githubusercontent.com/42935528/94761067-b9cc7100-03d6-11eb-96bc-4bcc06d40e33.png)

## Expected Result

Display of the chart for cube.visualize()
![image](https://user-images.githubusercontent.com/42935528/94761178-f4360e00-03d6-11eb-9212-89529d7e77a0.png)

## Environment

- atoti: 0.4.3
- Operating System: Windows 10
- Browser: Chrome
- Export PDF setup: https://nbconvert.readthedocs.io/en/latest/install.html

**Comment by tibdex** [comment]
Hi, indeed this is not supported but, if you use the HTML export feature of JupyterLab with our extension installed, you should get SVG snapshots of the widgets. What is your use case for converting a notebook to PDF?

**Comment by xpilasav** [comment]
Our prospect is building a notebook with code, charts, text, annotations, using it to work and analyze... and once he's done and happy with the results, he hides some part of the code and build a PDF right from Jupyter Lab to be sent to managers as a report...
I will try and suggest the HTML feature but checking if that is something that could/will/won't be supported

**Comment by mingkongwoo** [comment]
Hi, this is often a requirement to export to PDF reports for submitting to regulatory authorities, especially in risk management.

**Comment by tibdex** [comment]
Because our widget snapshots can be made of HTML tags such as `<div>`, we use the `text/html` mime type for them. However, this mime type is ignored by nbconvert when exporting to PDF (see https://github.com/jupyter/nbconvert/issues/474).

You can still get a PDF with these steps:
1. Save your notebook to trigger the snapshotting of the atoti widgets. 
2. File > Export Notebook As.. > HTML
3. Click on the downloaded HTML file to open it in your browser and <kbd>Ctrl</kbd>+<kbd>P</kbd> to save it as PDF.

With this technique, you will even get styled pandas DataFrames instead of their plain text representations by default.

**Comment by xpilasav** [comment]
Thank you. Will test it and talk to our prospect about it

**Comment by nithinreddyy** [comment]
> Thank you. Will test it and talk to our prospect about it

He, did you find the answer? I'm facing same issue, I'm unable to visualize the chart in jupyter lab.
![lab](https://user-images.githubusercontent.com/56256685/123383777-37618e00-d5b1-11eb-9e41-88c8645232ff.PNG)
