### ISSUE TITLE
Adding a tail function in the store.

### ISSUE THREAD

**Issue by rvs36** [atoti/atoti#164]
## Description

Adding a tail function in the store.

## Context

When I append rows to a store in order to check if the rows I would like to see if the rows have been appended accurately or not. And a tail feature will enable us to see something like store.head(nrows = -5) i.e. the bottom 5 rows.

**Comment by tibdex** [comment]
Hi Raghav, unlike a pandas DataFrame which has a clearly defined order for its rows, an atoti store doesn't provide strong order guarantees, especially when it is partitioned. What can be ordered is level members, using [`Level.comparator`](https://docs.atoti.io/0.5.1/lib/atoti.html#atoti.level.Level.comparator).

So we can't add a `tail` function. In fact, even our docs for `head` is misleading since it incorrectly says: "Return the first n rows of the store ..." while it should say "Return n rows of the store as a pandas DataFrame ...". We'll change that.
