### ISSUE TITLE
atoti.read_csv read data from .ipynb_checkpoints folder

### ISSUE THREAD

**Issue by dudu-creator** [atoti/atoti#166]
## Steps to reproduce
1. assuming I load test.csv from C:\Users\Junchao\data and data is loaded as usual
2. a folder called .ipynb_checkpoints will be created automatically in the path I specified in *1* at some point. Also test.csv will be presented in this folder.
3. I changed test.csv in C:\Users\Junchao\data and reload it but it doesn't return me a updated store with atoti
4. It turns out test.csv is loaded from .ipynb_checkpoints\ instead of the original folder I specified. 

## Expected Result
Data should always be loaded from the path specified. 
## Environment

- atoti: 0.4.3
- Python: 3.8.3
- Operating System: Win

**Comment by rcolle** [comment]
This sounds weird since:

1. `.ipynb_checkpoints` are only supposed to be created in the same directory as your notebook file (`.ipynb` file)
2. They should only contain `.ipynb` backups. 

See https://stackoverflow.com/questions/46421663/what-are-jupyter-notebook-checkpoint-files-for?rq=1

Can you please provide a reproduceable test case?

**Comment by dudu-creator** [comment]
Here is an example. I only have one line in trades_preprocessed_2020-01-17.csv, but the store loaded has multiple rows. 
[test.zip](https://github.com/atoti/atoti/files/5341222/test.zip)

Can we always avoid reading from .ipynb_checkpoints as it's a backup unless it's explicitly specified in a path?

Thanks,
Junchao

**Comment by fabiencelier** [comment]
The reason why it loads several files is because you use the folder path in `read_csv`, which loads all the `.csv` files in all subdirectories.
According to the [doc](https://docs.atoti.io/0.4.3/lib/atoti.html?highlight=read_csv#atoti.session.Session.read_csv):
> If a path pointing to a directory is provided, all of the files with the .csv extension in the directory and subdirectories will be loaded into the same store and, as such, they are all expected to share the same schema

So both `data/test.csv` and `data/.ipynb_checkpoints/test.csv` are loaded.

**Comment by dudu-creator** [comment]
I understand but shouldn't we avoid reading from ipynb_checkpoints as it's a backup folder?

**Comment by fabiencelier** [comment]
I was confused about why you have CSV files in this checkpoints folder as I though only notebooks with `.ipynb` extension where put in there. But I have just tried it myself and it appears that any file modified from jupyter will be put into this folder :( 

This can indeed create confusing behavior when using a directory path.

We could ignore by default all the `.ipynb_checkpoints` subdirectories, or even all the subdirectories starting by `.` if other tools have other caching names.

In the meantime there are some workarounds:
  - Use the path to the exact file
  - Use a glob pattern to ignore the directories starting with a `.` such as `"data/[!.]**.csv"`

**Comment by tibdex** [comment]
The `[!.]` in the glob pattern is the right way to go for now.
