### ISSUE TITLE
Improve documentation search

### ISSUE THREAD

**Issue by OPeyrusse** [atoti/atoti#168]
## Description

When searching information in atoti documentation website, the results almost always include website technical information like

> Docker
.../ } /* Fix math alignment, see https://github.com/rtfd/sphinx_rtd_theme/pull/686 */ .math { text-align: unset; } Docker atoti distributes an official image on DockerHub. It contains the atoti library and its JupyterLab extension read...

![search-1](https://user-images.githubusercontent.com/29573092/95744233-4f97b400-0c93-11eb-8fdf-ae1c052bc7fe.png)

It looks a bit messy, particularly when the search does not seems to return anything relevant except garbage.

![search-2](https://user-images.githubusercontent.com/29573092/95744127-29721400-0c93-11eb-957c-3674256741f7.png)

**Comment by tibdex** [comment]
Thanks for reporting this. Indeed this doesn't look good. The issue comes from [this code in nbsphinx](https://github.com/spatialaudio/nbsphinx/blob/2432715fbe5bceda46835feff010596be2f291b2/src/nbsphinx.py#L1908-L1922) that inlines some CSS near the page content that then creeps in the context provided by the search results.

However, even without this issue, Sphinx's built-in search mechanism isn't very good. It's not specific to the atoti project. For instance, when searching for "reset index" in pandas docs you get that:

<img width="1365" alt="Screen Shot 2021-01-28 at 18 52 31" src="https://user-images.githubusercontent.com/6574550/106178430-0d3ea800-619a-11eb-826e-d075f2092f77.png">

Which isn't very helpful.

With Google on the other hand, you get that:

<img width="724" alt="Screen Shot 2021-01-28 at 18 52 45" src="https://user-images.githubusercontent.com/6574550/106178465-1af42d80-619a-11eb-8f9a-eac4a37704b5.png">

which is exactly what you want.

We'll see what can be done to improve search results.

**Comment by OPeyrusse** [comment]
Understood. Thank for looking at it.
