### ISSUE TITLE
Missing information about automatic measure creation 

### ISSUE THREAD

**Issue by arielibaba** [atoti/atoti#169]
## Description

 When working on Atoti I created a cube (in auto mode) based on a first store and for which the following default measures where created (based on the numerical type column "quantity"): 
- quantity.SUM
- quantity.MEAN

And I created a new store and perform a join on the first one. Then, when I visualize the existing cube, I notice that the following default measures for the new numerical column (cost):
- cost.VALUES

I have searched on the documentation on the link below:
https://docs.atoti.io/0.4.3/lib/atoti.html#atoti.session.Session.create_cube

But, I could not find explanation about this difference.
Plus, I've found nothing related to this in any existing issue.

Please, could you help me understanding what happened in my case ?

Thank you in advance.
Ariel

**Comment by Skyscimitar** [comment]
Hello Ariel,
The new measure which is created appears because of the join. As such, the behavior for these new measures is documented with the join method: https://docs.atoti.io/0.4.3/lib/atoti.html?highlight=join#atoti.store.Store.join
We put the documentation for measures coming from joined stores because we felt a single docstring explaining the behavior of cube modes, plus the different behaviors for joined stores depending on the cube mode and mappings would be too complicated and intimidating.

**Comment by fabiencelier** [comment]
Maybe we can add a cell about this in the tuto, when we join with the product store.

It should add a "Purchase Price.VALUE" measure and we could make a query to show that this measure is only defined when the "Products" level is expressed, and that it is simply the value of the Purchase price in the store.

**Comment by jbe456** [comment]
@Skyscimitar I don't see [in the documentation link you provided](https://docs.atoti.io/0.4.3/lib/atoti.html?highlight=join#atoti.store.Store.join) a reference or an explanation for the numerical fields being converted to `VALUE` instead of `SUM` and `MEAN`. Am I missing something? 

Could you remind me why we do not create `SUM` and `MEAN` for numeric columns when they belong to joined stores?

**Comment by fabiencelier** [comment]
What is `field.VALUE` will be clarified in the tutorial of the next version
