### ISSUE TITLE
Automatically bucket date hierarchy

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#171]
## Description

When you set the type of a field as local date, it would be nice to create multi-level hierarchy containing year - month - day (hour - minute - second) for this field in order to bucket the date more easily.
Nevertheless until AUI5 is released, if you could keep the hierarchy as we have as of today in order to see all the dates all member and the dates filters. Please refer to this ticket for the all member issue https://support.activeviam.com/jira/projects/UI/issues/UI-4576.

## Context

Every projects contains dates field and if we want to bucket those we need to pre-process the date our self even though we have to specify date type on datastore.

**Comment by fabiencelier** [comment]
related to https://github.com/activeviam/atoti/issues/517

**Comment by fabiencelier** [comment]
https://github.com/atoti/atoti/issues/181 also mentions quarter and week number

**Comment by fabiencelier** [comment]
This will be available in the next release (and next continuous build) as a experimental feature.

You can use it with 

```python
tt.experimental.create_date_hierarchy(
          "NewDateHierarchy",
          cube,
          store["Date"],
          levels={"Year": "Y", "Month": "MMMM", "Day": "d"},
)
```

**Comment by amhatre** [comment]
Thanks for adding this feature. We need it for a client migrating from ActivePivot to Atoti+. Can this be moved from experimental to a real atoti feature?

**Comment by tibdex** [comment]
Hi Amit, the creation of the date hierarchy could also be done in a preprocessing step by adding the corresponding date parts columns before loading the data into an atoti store.
Usually, we consider preprocessing to be outside the scope of atoti and that's why this feature is experimental.

On the other hand, we know that this is a common need and that it's convenient to be able to do it directly inside atoti.

We haven't decided yet whether this feature will be stabilized, changed, or dropped.
