### ISSUE TITLE
Unclear message in the loading report

### ISSUE THREAD

**Issue by APolyakova** [atoti/atoti#185]
Hello

I'm getting loading error messages, however I'm struggling to resolve the issues, as the message is unclear:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/37184538/99200675-a0e80700-275b-11eb-80eb-753517c0826b.png">

Challenges:
- there seems to be a typo - instead of "column review_store" should there be "datastore review_store"?
- I checked the lines in the dataframe with the indexes -25222, 27962 and 57563 - however they don't contain the date strings mentioned in the error message.
- I have multiple columns with dates - so not sure which date is problematic. Both columns were assigned type "LocalDateTime[yyyy-MM-dd HH:mm:ss]" in atoti.

I searched for the date strings in the data - found the following two and they look ok.

```
reviews_df[reviews_df.review_answer_timestamp.dt.strftime("%Y-%m-%d %H:%M:%S").isin(["2017-09-21 12:25:26", "2017-09-21 12:25:26", "2017-09-11 01:28:36"])]
```

<img width="605" alt="image" src="https://user-images.githubusercontent.com/37184538/99200845-a09c3b80-275c-11eb-86b9-34f981acd76f.png">

Data set is Public Olist data set form kaggle: https://www.kaggle.com/olistbr/brazilian-ecommerce?select=olist_order_reviews_dataset.csv

Code snippet to generate error message:

```
import atoti
import pandas as pd



session = atoti.create_session()
ds = session.read_pandas(
    pd.read_csv(
        './data/csv/olist_order_reviews_dataset.csv',
        parse_dates=["review_creation_date", "review_answer_timestamp"],
        date_parser=pd.to_datetime,
    ),
     store_name="reviews", keys=["review_id", "order_id"]
)
cube = session.create_cube(ds, "Analytics")
session.load_all_data()
ds.loading_report
```

**Comment by fabiencelier** [comment]
> there seems to be a typo - instead of "column review_store" should there be "datastore review_store"?

There is no typo, the issue is with the column "review_score" of your store "reviews"

> I searched for the date strings in the data - found the following two and they look ok.

Searching for the erroneous dates in the CSV file I have found that is is always on a row with a multiline string such as this one line 26752 for  `2017-03-21 00:24:02`:

<pre>
"90085d461e26c5995a533fe2f6633332","3f8f3b3ace5d3cf820f9d891b366f621",5,,"Fiquei com receio de fazer essa comora >pela Internet,mas fiz e vi que valeu a pena.Produto entregue mais cedo que o previsto e com todo informação durante seu >transporte.Parabéns targaryen e lannister.
",2017-03-14 00:00:00,2017-03-21 00:24:02
</pre>

This should not be an issue because the field is correctly wrapped into double quotes, and loading directly the CSV without pandas works:

```python
ds2 = session.read_csv(
    '/home/fabien/Downloads/olist_order_reviews_dataset.csv',
    keys=["review_id", "order_id"]
)
```

But when we load the pandas we use a temporary CSV file which is different from the initial CSV: there is no double quotes `"` for the multiline strings:

<pre>
90085d461e26c5995a533fe2f6633332|3f8f3b3ace5d3cf820f9d891b366f621|5||Fiquei com receio de fazer essa comora pela Internet,mas fiz e vi que valeu a pena.Produto entregue mais cedo que o previsto e com todo informação durante seu transporte.Parabéns targaryen e lannister.
|2017-03-14 00:00:00|2017-03-21 00:24:02
</pre>

In this case the date which is supposed to be in the last column end up in the 3rd column of the following row. The 3rd column is `review_score` which is an integer and fails to parse the date.

I will investigate more but we should probably use double quotes on all our string fields when writing the temporary CSV file.

**Comment by fabiencelier** [comment]
After investigating, I have found that pandas correctly escape the fields containing `\n` with double quotes. However the 3 problematic lines of your CSV contains a `\r` character which is not escaped when writing the temporary files but considered as a new line character by atoti.

I have detailed the bug and how to reproduce it in an other specific issue #186

**Comment by APolyakova** [comment]
Thank you for looking into it @Fabien.
