### ISSUE TITLE
Publish in app should open in the current Jupyter Lab window

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#194]
## Steps to reproduce

Currently if I click on the app's URL from the message after publishing the widget, the app opens up in the browser of the Jupyter lab instead of a new browser. I thought it is better in the old version, where a new tab is opened up instead.

![open_in_current_browser](https://user-images.githubusercontent.com/35210495/102057332-b880e100-3e28-11eb-9378-c05f7ebd4db8.gif)

## Environment
- atoti: 0.5.0
- Operating System: win32

**Comment by tibdex** [comment]
Hi Hui Fang,

The default behavior for links on the web is to open in the same tab so that's what we did here. But indeed, more and more, web apps try to prevent users accidentally replacing the current app by another website when clicking on a link. Besides, when you do `session.url` and click on the outputted link, it does in fact open in a new tab.

It's thus debatable whether this link to the app should also open in a new tab by default.

In the meantime, as for any web link, you can use <kbd>ctrl</kbd> click or right click to open it in a new tab.
