### ISSUE TITLE
conda atoti upgrade not working

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#209]
## Steps to reproduce

I have an existing environment with atoti 0.5.0 and I tried to use `conda update atoti` as suggested in https://stackoverflow.com/a/64702238.

Below are the update printed stack:
<details><pre>
(atoti) C:\Users\Yeo Hui Fang\Documents\GitHub\notebooks>conda update atoti
Collecting package metadata (current_repodata.json): done
Solving environment: |
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/win-64::arrow-cpp==2.0.0=py37h0dac82d_6_cpu
  - https://conda.atoti.io/noarch::atoti==0.5.0=539610c
  - https://conda.atoti.io/noarch::atoti-jupyterlab==0.5.0=539610c
  - conda-forge/noarch::babel==2.9.0=pyhd3deb0d_0
  - https://conda.atoti.io/noarch::jupyterlab==3.0.0rc10=pyh5fc60ef_0
  - https://conda.atoti.io/noarch::jupyterlab_server==2.0.0rc3=pyh70d38ba_0
  - conda-forge/win-64::pandas==1.1.5=py37h08fd248_0
  - conda-forge/noarch::parquet-cpp==1.5.1=2
  - conda-forge/win-64::pyarrow==2.0.0=py37h633fffd_6_cpu
  - conda-forge/win-64::selenium==3.141.0=py37h4ab8f01_1002
done

## Package Plan ##

  environment location: C:\Apps\miniconda3\envs\atoti

  added / updated specs:
    - atoti

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anyio-2.0.2                |   py37h03978a9_4         110 KB  conda-forge
    brotli-1.0.9               |       h0e60522_4         882 KB  conda-forge
    brotlipy-0.7.0             |py37hcc03f2d_1001         368 KB  conda-forge
    certifi-2020.12.5          |   py37h03978a9_1         143 KB  conda-forge
    chardet-4.0.0              |   py37h03978a9_1         215 KB  conda-forge
    cryptography-3.3.1         |   py37hd8e9650_1         593 KB  conda-forge
    importlib-metadata-3.4.0   |   py37h03978a9_0          21 KB  conda-forge
    importlib_metadata-3.4.0   |       hd8ed1ab_0           3 KB  conda-forge
    jedi-0.18.0                |   py37h03978a9_2         925 KB  conda-forge
    jupyter_client-6.1.11      |     pyhd8ed1ab_1          76 KB  conda-forge
    jupyter_server-1.2.1       |   py37h03978a9_0         270 KB  conda-forge
    libblas-3.9.0              |            7_mkl         3.9 MB  conda-forge
    libcblas-3.9.0             |            7_mkl         3.9 MB  conda-forge
    liblapack-3.9.0            |            7_mkl         3.9 MB  conda-forge
    markupsafe-1.1.1           |   py37hcc03f2d_3          30 KB  conda-forge
    mistune-0.8.4              |py37hcc03f2d_1003          54 KB  conda-forge
    nbclassic-0.2.6            |     pyhd8ed1ab_0          17 KB  conda-forge
    notebook-6.2.0             |   py37h03978a9_0         7.5 MB  conda-forge
    numpy-1.19.5               |   py37hd20adf4_1         4.8 MB  conda-forge
    pandoc-2.11.3.2            |       h8ffe710_0        17.3 MB  conda-forge
    parso-0.8.1                |     pyhd8ed1ab_0          67 KB  conda-forge
    prompt-toolkit-3.0.10      |     pyha770c72_0         237 KB  conda-forge
    pyrsistent-0.17.3          |   py37hcc03f2d_2          91 KB  conda-forge
    pysocks-1.7.1              |   py37h03978a9_3          28 KB  conda-forge
    pywin32-228                |   py37hcc03f2d_1         7.0 MB  conda-forge
    pyyaml-5.3.1               |   py37hcc03f2d_2         160 KB  conda-forge
    setuptools-49.6.0          |   py37h03978a9_3         931 KB  conda-forge
    sniffio-1.2.0              |   py37h03978a9_1          15 KB  conda-forge
    terminado-0.9.2            |   py37h03978a9_0          26 KB  conda-forge
    tornado-6.1                |   py37hcc03f2d_1         648 KB  conda-forge
    win_inet_pton-1.1.0        |   py37h03978a9_2           8 KB  conda-forge
    wincertstore-0.2           |py37h03978a9_1006          15 KB  conda-forge
    zstd-1.4.8                 |       h498f385_0         958 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        55.1 MB

The following NEW packages will be INSTALLED:

  anyio              conda-forge/win-64::anyio-2.0.2-py37h03978a9_4
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  jedi               conda-forge/win-64::jedi-0.18.0-py37h03978a9_2
  numpy              conda-forge/win-64::numpy-1.19.5-py37hd20adf4_1
  parso              conda-forge/noarch::parso-0.8.1-pyhd8ed1ab_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.10-pyha770c72_0
  pytz               conda-forge/noarch::pytz-2020.5-pyhd8ed1ab_0
  requests           conda-forge/noarch::requests-2.25.1-pyhd3deb0d_0
  sniffio            conda-forge/win-64::sniffio-1.2.0-py37h03978a9_1
  urllib3            conda-forge/noarch::urllib3-1.26.2-pyhd8ed1ab_0

The following packages will be UPDATED:

  brotli                                   1.0.9-ha925a31_3 --> 1.0.9-h0e60522_4
  certifi                          2020.12.5-py37h03978a9_0 --> 2020.12.5-py37h03978a9_1
  chardet                           3.0.4-py37hf50a25e_1008 --> 4.0.0-py37h03978a9_1
  cryptography                         3.3.1-py37hd8e9650_0 --> 3.3.1-py37hd8e9650_1
  importlib-metadata conda-forge/noarch::importlib-metadat~ --> conda-forge/win-64::importlib-metadata-3.4.0-py37h03978a9_0
  importlib_metadata                       3.1.1-hd8ed1ab_0 --> 3.4.0-hd8ed1ab_0
  ipython                                      5.8.0-py37_1 --> 7.19.0-py37heaed05f_0
  jupyter_client                                 6.1.7-py_0 --> 6.1.11-pyhd8ed1ab_1
  jupyter_server                      1.0.10-py37h03978a9_0 --> 1.2.1-py37h03978a9_0
  libblas                                      3.8.0-21_mkl --> 3.9.0-7_mkl
  libcblas                                     3.8.0-21_mkl --> 3.9.0-7_mkl
  liblapack                                    3.8.0-21_mkl --> 3.9.0-7_mkl
  libutf8proc                              2.6.0-hcb41399_0 --> 2.6.1-hcb41399_0
  markupsafe                           1.1.1-py37h0013d47_2 --> 1.1.1-py37hcc03f2d_3
  mistune                           0.8.4-py37hcc03f2d_1002 --> 0.8.4-py37hcc03f2d_1003
  nbclassic                              0.2.4-pyhd8ed1ab_0 --> 0.2.6-pyhd8ed1ab_0
  notebook                             6.1.5-py37h03978a9_0 --> 6.2.0-py37h03978a9_0
  pandoc                                  2.11.2-h8ffe710_0 --> 2.11.3.2-h8ffe710_0
  pip                                   20.3.1-pyhd8ed1ab_0 --> 20.3.3-pyhd8ed1ab_0
  pyopenssl                             20.0.0-pyhd8ed1ab_0 --> 20.0.1-pyhd8ed1ab_0
  pyrsistent                          0.17.3-py37hcc03f2d_1 --> 0.17.3-py37hcc03f2d_2
  pysocks                              1.7.1-py37hf50a25e_2 --> 1.7.1-py37h03978a9_3
  pywin32                                228-py37h4ab8f01_0 --> 228-py37hcc03f2d_1
  pyyaml                               5.3.1-py37h0013d47_1 --> 5.3.1-py37hcc03f2d_2
  setuptools                          49.6.0-py37hf50a25e_2 --> 49.6.0-py37h03978a9_3
  terminado                            0.9.1-py37h03978a9_1 --> 0.9.2-py37h03978a9_0
  tornado                                6.1-py37hcc03f2d_0 --> 6.1-py37hcc03f2d_1
  vc                                        14.1-h869be7e_1 --> 14.2-hb210afc_2
  vs2015_runtime                     14.16.27012-h30e32a0_2 --> 14.28.29325-h5e1d092_0
  win_inet_pton                        1.1.0-py37hc8dfbb8_1 --> 1.1.0-py37h03978a9_2
  wincertstore                        0.2-py37hc8dfbb8_1005 --> 0.2-py37h03978a9_1006
  zstd                                     1.4.5-h1f3a1b7_2 --> 1.4.8-h498f385_0

The following packages will be SUPERSEDED by a higher-priority channel:

  m2w64-gcc-libgfor~                             pkgs/msys2 --> conda-forge
  m2w64-gcc-libs                                 pkgs/msys2 --> conda-forge
  m2w64-gcc-libs-co~                             pkgs/msys2 --> conda-forge
  m2w64-gmp                                      pkgs/msys2 --> conda-forge
  m2w64-libwinpthre~                             pkgs/msys2 --> conda-forge
  msys2-conda-epoch                              pkgs/msys2 --> conda-forge

The following packages will be DOWNGRADED:

  brotlipy                          0.7.0-py37h0013d47_1001 --> 0.7.0-py37hcc03f2d_1001

Proceed ([y]/n)? y

Downloading and Extracting Packages
pywin32-228          | 7.0 MB    | ######################################################################################################################### | 100%
pandoc-2.11.3.2      | 17.3 MB   | ######################################################################################################################### | 100%
parso-0.8.1          | 67 KB     | ######################################################################################################################### | 100%
jupyter_client-6.1.1 | 76 KB     | ######################################################################################################################### | 100%
nbclassic-0.2.6      | 17 KB     | ######################################################################################################################### | 100%
brotli-1.0.9         | 882 KB    | ######################################################################################################################### | 100%
importlib_metadata-3 | 3 KB      | ######################################################################################################################### | 100%
terminado-0.9.2      | 26 KB     | ######################################################################################################################### | 100%
notebook-6.2.0       | 7.5 MB    | ######################################################################################################################### | 100%
markupsafe-1.1.1     | 30 KB     | ######################################################################################################################### | 100%
anyio-2.0.2          | 110 KB    | ######################################################################################################################### | 100%
setuptools-49.6.0    | 931 KB    | ######################################################################################################################### | 100%
libcblas-3.9.0       | 3.9 MB    | ######################################################################################################################### | 100%
sniffio-1.2.0        | 15 KB     | ######################################################################################################################### | 100%
prompt-toolkit-3.0.1 | 237 KB    | ######################################################################################################################### | 100%
libblas-3.9.0        | 3.9 MB    | ######################################################################################################################### | 100%
pyrsistent-0.17.3    | 91 KB     | ######################################################################################################################### | 100%
cryptography-3.3.1   | 593 KB    | ######################################################################################################################### | 100%
chardet-4.0.0        | 215 KB    | ######################################################################################################################### | 100%
liblapack-3.9.0      | 3.9 MB    | ######################################################################################################################### | 100%
brotlipy-0.7.0       | 368 KB    | ######################################################################################################################### | 100%
win_inet_pton-1.1.0  | 8 KB      | ######################################################################################################################### | 100%
numpy-1.19.5         | 4.8 MB    | ######################################################################################################################### | 100%
wincertstore-0.2     | 15 KB     | ######################################################################################################################### | 100%
jedi-0.18.0          | 925 KB    | ######################################################################################################################### | 100%
pysocks-1.7.1        | 28 KB     | ######################################################################################################################### | 100%
importlib-metadata-3 | 21 KB     | ######################################################################################################################### | 100%
mistune-0.8.4        | 54 KB     | ######################################################################################################################### | 100%
pyyaml-5.3.1         | 160 KB    | ######################################################################################################################### | 100%
certifi-2020.12.5    | 143 KB    | ######################################################################################################################### | 100%
tornado-6.1          | 648 KB    | ######################################################################################################################### | 100%
jupyter_server-1.2.1 | 270 KB    | ######################################################################################################################### | 100%
zstd-1.4.8           | 958 KB    | ######################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
</pre></details>

The environment remains as 0.5.0 after the upgrade completed.
<details><pre>
(atoti) C:\Users\Yeo Hui Fang>conda list
# packages in environment at C:\Apps\miniconda3\envs\atoti:
#
# Name                    Version                   Build  Channel
abseil-cpp                20200225.2           ha925a31_2    conda-forge
anyio                     2.0.2            py37h03978a9_4    conda-forge
argon2-cffi               20.1.0           py37hcc03f2d_2    conda-forge
arrow-cpp                 2.0.0           py37h0dac82d_6_cpu    conda-forge
async_generator           1.10                       py_0    conda-forge
atoti                     0.5.0                   539610c    https://conda.atoti.io
atoti-aws                 0.5.0                    pypi_0    pypi
atoti-jupyterlab          0.5.0                   539610c    https://conda.atoti.io
</pre></details>

**Comment by tibdex** [comment]
Hi Hui Fang, I just tried:

<details>
<summary>conda install atoti=0.5.0 atoti-jupyterlab=0.5.0</summary>
<pre>
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/Caskroom/miniconda/base/envs/upgradito

  added / updated specs:
    - atoti-jupyterlab=0.5.0
    - atoti=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anyio-2.0.2                |   py39h6e9494a_4         111 KB  conda-forge
    appnope-0.1.2              |   py39h6e9494a_1          10 KB  conda-forge
    argon2-cffi-20.1.0         |   py39hcbf5805_2          45 KB  conda-forge
    arrow-cpp-2.0.0            |py39hcf4c6ca_16_cpu        15.9 MB  conda-forge
    atoti-0.5.0                |          539610c       130.2 MB  https://conda.atoti.io
    atoti-jupyterlab-0.5.0     |          539610c         1.6 MB  https://conda.atoti.io
    aws-c-cal-0.4.5            |       ha1a74bd_4          29 KB  conda-forge
    aws-c-common-0.4.65        |       h35c211d_0         145 KB  conda-forge
    aws-c-event-stream-0.2.6   |       h142b3dd_1          40 KB  conda-forge
    aws-c-io-0.8.0             |       h3654196_0         105 KB  conda-forge
    aws-checksums-0.1.10       |       h3654196_2          48 KB  conda-forge
    aws-sdk-cpp-1.8.122        |       hd5fcc58_0         2.0 MB  conda-forge
    brotlipy-0.7.0             |py39hcbf5805_1001         357 KB  conda-forge
    cffi-1.14.4                |   py39h7786acb_1         219 KB  conda-forge
    chardet-4.0.0              |   py39h6e9494a_1         204 KB  conda-forge
    cryptography-3.3.1         |   py39h79a2c39_1         612 KB  conda-forge
    grpc-cpp-1.34.1            |       h1671c54_0         2.5 MB  conda-forge
    importlib-metadata-3.4.0   |   py39h6e9494a_0          20 KB  conda-forge
    ipykernel-5.4.2            |   py39h71a6800_0         166 KB  conda-forge
    ipython-7.19.0             |   py39h71a6800_0         1.1 MB  conda-forge
    jedi-0.18.0                |   py39h6e9494a_2         932 KB  conda-forge
    jupyter_core-4.7.0         |   py39h6e9494a_0          72 KB  conda-forge
    jupyter_server-1.2.1       |   py39h6e9494a_0         243 KB  conda-forge
    libgfortran-5.0.0          |9_3_0_h6c81a4c_16          19 KB  conda-forge
    libgfortran5-9.3.0         |      h6c81a4c_16         1.7 MB  conda-forge
    markupsafe-1.1.1           |   py39hcbf5805_3          25 KB  conda-forge
    mistune-0.8.4              |py39hcbf5805_1003          54 KB  conda-forge
    nbconvert-6.0.7            |   py39h6e9494a_3         530 KB  conda-forge
    notebook-6.2.0             |   py39h6e9494a_0         6.3 MB  conda-forge
    pandas-1.2.0               |   py39h089d6f7_1        10.7 MB  conda-forge
    pyarrow-2.0.0              |py39h04a5ccc_16_cpu         2.2 MB  conda-forge
    pyrsistent-0.17.3          |   py39hcbf5805_2          87 KB  conda-forge
    pysocks-1.7.1              |   py39h6e9494a_3          27 KB  conda-forge
    pyzmq-20.0.0               |   py39hd6373f1_1         453 KB  conda-forge
    sniffio-1.2.0              |   py39h6e9494a_1          15 KB  conda-forge
    terminado-0.9.2            |   py39h6e9494a_0          26 KB  conda-forge
    tornado-6.1                |   py39hcbf5805_1         646 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       179.4 MB

The following NEW packages will be INSTALLED:

  abseil-cpp         conda-forge/osx-64::abseil-cpp-20200923.2-h046ec9c_1
  anyio              conda-forge/osx-64::anyio-2.0.2-py39h6e9494a_4
  appnope            conda-forge/osx-64::appnope-0.1.2-py39h6e9494a_1
  argon2-cffi        conda-forge/osx-64::argon2-cffi-20.1.0-py39hcbf5805_2
  arrow-cpp          conda-forge/osx-64::arrow-cpp-2.0.0-py39hcf4c6ca_16_cpu
  async_generator    conda-forge/noarch::async_generator-1.10-py_0
  atoti              None/noarch::atoti-0.5.0-539610c
  atoti-jupyterlab   None/noarch::atoti-jupyterlab-0.5.0-539610c
  attrs              conda-forge/noarch::attrs-20.3.0-pyhd3deb0d_0
  aws-c-cal          conda-forge/osx-64::aws-c-cal-0.4.5-ha1a74bd_4
  aws-c-common       conda-forge/osx-64::aws-c-common-0.4.65-h35c211d_0
  aws-c-event-stream conda-forge/osx-64::aws-c-event-stream-0.2.6-h142b3dd_1
  aws-c-io           conda-forge/osx-64::aws-c-io-0.8.0-h3654196_0
  aws-checksums      conda-forge/osx-64::aws-checksums-0.1.10-h3654196_2
  aws-sdk-cpp        conda-forge/osx-64::aws-sdk-cpp-1.8.122-hd5fcc58_0
  babel              conda-forge/noarch::babel-2.9.0-pyhd3deb0d_0
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0
  backports          conda-forge/noarch::backports-1.0-py_2
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.1-py_0
  bleach             conda-forge/noarch::bleach-3.2.1-pyh9f0ad1d_0
  brotli             conda-forge/osx-64::brotli-1.0.9-h046ec9c_4
  brotlipy           conda-forge/osx-64::brotlipy-0.7.0-py39hcbf5805_1001
  bzip2              conda-forge/osx-64::bzip2-1.0.8-hc929b4f_4
  c-ares             conda-forge/osx-64::c-ares-1.17.1-hc929b4f_0
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.12.5-h033912b_0
  certifi            conda-forge/osx-64::certifi-2020.12.5-py39h6e9494a_1
  cffi               conda-forge/osx-64::cffi-1.14.4-py39h7786acb_1
  chardet            conda-forge/osx-64::chardet-4.0.0-py39h6e9494a_1
  cryptography       conda-forge/osx-64::cryptography-3.3.1-py39h79a2c39_1
  decorator          conda-forge/noarch::decorator-4.4.2-py_0
  defusedxml         conda-forge/noarch::defusedxml-0.6.0-py_0
  entrypoints        conda-forge/noarch::entrypoints-0.3-pyhd8ed1ab_1003
  freetype           conda-forge/osx-64::freetype-2.10.4-h3f75d11_0
  gflags             conda-forge/osx-64::gflags-2.2.2-hb1e8313_1004
  glog               conda-forge/osx-64::glog-0.4.0-hb7f4fc5_3
  graphviz           conda-forge/osx-64::graphviz-2.42.3-h98dfb87_0
  grpc-cpp           conda-forge/osx-64::grpc-cpp-1.34.1-h1671c54_0
  idna               conda-forge/noarch::idna-2.10-pyh9f0ad1d_0
  importlib-metadata conda-forge/osx-64::importlib-metadata-3.4.0-py39h6e9494a_0
  importlib_metadata conda-forge/noarch::importlib_metadata-3.4.0-hd8ed1ab_0
  ipykernel          conda-forge/osx-64::ipykernel-5.4.2-py39h71a6800_0
  ipython            conda-forge/osx-64::ipython-7.19.0-py39h71a6800_0
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1
  jdk4py             None/osx-64::jdk4py-11.0.7.3-py39_0
  jedi               conda-forge/osx-64::jedi-0.18.0-py39h6e9494a_2
  jinja2             conda-forge/noarch::jinja2-2.11.2-pyh9f0ad1d_0
  jpeg               conda-forge/osx-64::jpeg-9d-hbcb3906_0
  json5              conda-forge/noarch::json5-0.9.5-pyh9f0ad1d_0
  jsonschema         conda-forge/noarch::jsonschema-3.2.0-py_2
  jupyter_client     conda-forge/noarch::jupyter_client-6.1.11-pyhd8ed1ab_1
  jupyter_core       conda-forge/osx-64::jupyter_core-4.7.0-py39h6e9494a_0
  jupyter_server     conda-forge/osx-64::jupyter_server-1.2.1-py39h6e9494a_0
  jupyterlab         None/noarch::jupyterlab-3.0.0rc10-pyh5fc60ef_0
  jupyterlab_pygmen~ conda-forge/noarch::jupyterlab_pygments-0.1.2-pyh9f0ad1d_0
  jupyterlab_server  None/noarch::jupyterlab_server-2.0.0rc3-pyh70d38ba_0
  krb5               conda-forge/osx-64::krb5-1.17.2-h60d9502_0
  libblas            conda-forge/osx-64::libblas-3.9.0-7_openblas
  libcblas           conda-forge/osx-64::libcblas-3.9.0-7_openblas
  libcurl            conda-forge/osx-64::libcurl-7.71.1-h9bf37e3_8
  libcxx             conda-forge/osx-64::libcxx-11.0.0-h4c3b8ed_1
  libedit            conda-forge/osx-64::libedit-3.1.20191231-h0678c8f_2
  libev              conda-forge/osx-64::libev-4.33-haf1e3a3_1
  libevent           conda-forge/osx-64::libevent-2.1.10-hddc9c9b_3
  libffi             conda-forge/osx-64::libffi-3.3-h046ec9c_2
  libgfortran        conda-forge/osx-64::libgfortran-5.0.0-9_3_0_h6c81a4c_16
  libgfortran5       conda-forge/osx-64::libgfortran5-9.3.0-h6c81a4c_16
  liblapack          conda-forge/osx-64::liblapack-3.9.0-7_openblas
  libnghttp2         conda-forge/osx-64::libnghttp2-1.41.0-h7580e61_2
  libopenblas        conda-forge/osx-64::libopenblas-0.3.12-openmp_h54245bb_1
  libpng             conda-forge/osx-64::libpng-1.6.37-h7cec526_2
  libprotobuf        conda-forge/osx-64::libprotobuf-3.14.0-hfd3ada9_0
  libsodium          conda-forge/osx-64::libsodium-1.0.18-hbcb3906_1
  libssh2            conda-forge/osx-64::libssh2-1.9.0-h8a08a2b_5
  libthrift          conda-forge/osx-64::libthrift-0.13.0-h990abc0_6
  libtiff            conda-forge/osx-64::libtiff-4.2.0-h355d032_0
  libutf8proc        conda-forge/osx-64::libutf8proc-2.6.1-h35c211d_0
  libwebp-base       conda-forge/osx-64::libwebp-base-1.1.0-hbcb3906_3
  llvm-openmp        conda-forge/osx-64::llvm-openmp-11.0.0-h73239a0_1
  lz4-c              conda-forge/osx-64::lz4-c-1.9.3-h046ec9c_0
  markupsafe         conda-forge/osx-64::markupsafe-1.1.1-py39hcbf5805_3
  mistune            conda-forge/osx-64::mistune-0.8.4-py39hcbf5805_1003
  nbclassic          conda-forge/noarch::nbclassic-0.2.6-pyhd8ed1ab_0
  nbclient           conda-forge/noarch::nbclient-0.5.1-py_0
  nbconvert          conda-forge/osx-64::nbconvert-6.0.7-py39h6e9494a_3
  nbformat           conda-forge/noarch::nbformat-5.0.8-py_0
  ncurses            conda-forge/osx-64::ncurses-6.2-h2e338ed_4
  nest-asyncio       conda-forge/noarch::nest-asyncio-1.4.3-pyhd8ed1ab_0
  notebook           conda-forge/osx-64::notebook-6.2.0-py39h6e9494a_0
  numpy              conda-forge/osx-64::numpy-1.19.5-py39he588a01_1
  openssl            conda-forge/osx-64::openssl-1.1.1i-h35c211d_0
  orc                conda-forge/osx-64::orc-1.6.6-h675e114_1
  packaging          conda-forge/noarch::packaging-20.8-pyhd3deb0d_0
  pandas             conda-forge/osx-64::pandas-1.2.0-py39h089d6f7_1
  pandoc             conda-forge/osx-64::pandoc-2.11.3.2-h35c211d_0
  pandocfilters      conda-forge/noarch::pandocfilters-1.4.2-py_1
  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1-2
  parso              conda-forge/noarch::parso-0.8.1-pyhd8ed1ab_0
  pexpect            conda-forge/noarch::pexpect-4.8.0-pyh9f0ad1d_2
  pickleshare        conda-forge/noarch::pickleshare-0.7.5-py_1003
  pip                conda-forge/noarch::pip-20.3.3-pyhd8ed1ab_0
  prometheus_client  conda-forge/noarch::prometheus_client-0.9.0-pyhd3deb0d_0
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.10-pyha770c72_0
  ptyprocess         conda-forge/noarch::ptyprocess-0.7.0-pyhd3deb0d_0
  pyarrow            conda-forge/osx-64::pyarrow-2.0.0-py39h04a5ccc_16_cpu
  pycparser          conda-forge/noarch::pycparser-2.20-pyh9f0ad1d_2
  pygments           conda-forge/noarch::pygments-2.7.3-pyhd8ed1ab_0
  pyopenssl          conda-forge/noarch::pyopenssl-20.0.1-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.7-pyh9f0ad1d_0
  pyrsistent         conda-forge/osx-64::pyrsistent-0.17.3-py39hcbf5805_2
  pysocks            conda-forge/osx-64::pysocks-1.7.1-py39h6e9494a_3
  python             conda-forge/osx-64::python-3.9.1-h1d169a7_3_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/osx-64::python_abi-3.9-1_cp39
  pytz               conda-forge/noarch::pytz-2020.5-pyhd8ed1ab_0
  pyyaml             conda-forge/osx-64::pyyaml-5.3.1-py39hcbf5805_2
  pyzmq              conda-forge/osx-64::pyzmq-20.0.0-py39hd6373f1_1
  re2                conda-forge/osx-64::re2-2020.11.01-h2e338ed_0
  readline           conda-forge/osx-64::readline-8.0-h0678c8f_2
  requests           conda-forge/noarch::requests-2.25.1-pyhd3deb0d_0
  send2trash         conda-forge/noarch::send2trash-1.5.0-py_0
  setuptools         conda-forge/osx-64::setuptools-49.6.0-py39h6e9494a_3
  six                conda-forge/noarch::six-1.15.0-pyh9f0ad1d_0
  snappy             conda-forge/osx-64::snappy-1.1.8-hb1e8313_3
  sniffio            conda-forge/osx-64::sniffio-1.2.0-py39h6e9494a_1
  sqlite             conda-forge/osx-64::sqlite-3.34.0-h17101e1_0
  terminado          conda-forge/osx-64::terminado-0.9.2-py39h6e9494a_0
  testpath           conda-forge/noarch::testpath-0.4.4-py_0
  tk                 conda-forge/osx-64::tk-8.6.10-h0419947_1
  tornado            conda-forge/osx-64::tornado-6.1-py39hcbf5805_1
  traitlets          conda-forge/noarch::traitlets-5.0.5-py_0
  typeguard          conda-forge/noarch::typeguard-2.9.1-py_0
  typing_extensions  conda-forge/noarch::typing_extensions-3.7.4.3-py_0
  tzdata             conda-forge/noarch::tzdata-2020f-he74cb21_0
  urllib3            conda-forge/noarch::urllib3-1.26.2-pyhd8ed1ab_0
  wcwidth            conda-forge/noarch::wcwidth-0.2.5-pyh9f0ad1d_2
  webencodings       conda-forge/noarch::webencodings-0.5.1-py_1
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/osx-64::xz-5.2.5-haf1e3a3_1
  yaml               conda-forge/osx-64::yaml-0.2.5-haf1e3a3_0
  zeromq             conda-forge/osx-64::zeromq-4.3.3-h74dc148_3
  zipp               conda-forge/noarch::zipp-3.4.0-py_0
  zlib               conda-forge/osx-64::zlib-1.2.11-h7795811_1010
  zstd               conda-forge/osx-64::zstd-1.4.8-hf387650_1


Proceed ([y]/n)? y
</pre>
</details>

<details>
<summary>conda update atoti atoti-jupyterlab</summary>
<pre>
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/Caskroom/miniconda/base/envs/upgradito

  added / updated specs:
    - atoti
    - atoti-jupyterlab


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    atoti-0.5.1                |          7f32d5e       130.9 MB  https://conda.atoti.io
    atoti-jupyterlab-0.5.1     |          7f32d5e         2.6 MB  https://conda.atoti.io
    jupyterlab-3.0.4           |     pyhd8ed1ab_0         5.8 MB  conda-forge
    jupyterlab_server-2.1.2    |     pyhd8ed1ab_0          37 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       139.3 MB

The following packages will be UPDATED:

  atoti                                       0.5.0-539610c --> 0.5.1-7f32d5e
  atoti-jupyterlab                            0.5.0-539610c --> 0.5.1-7f32d5e
  jdk4py                                    11.0.7.3-py39_0 --> 11.0.9.0-py39_0
  jupyterlab            ::jupyterlab-3.0.0rc10-pyh5fc60ef_0 --> conda-forge::jupyterlab-3.0.4-pyhd8ed1ab_0
  jupyterlab_server  ::jupyterlab_server-2.0.0rc3-pyh70d38~ --> conda-forge::jupyterlab_server-2.1.2-pyhd8ed1ab_0


Proceed ([y]/n)? y

</pre>
</details>

and didn't run into any issues.

Can you try with `conda update atoti atoti-jupyterlab` too instead of just `conda update atoti`?

**Comment by HuifangYeo** [comment]
Hi Thibault,

I managed to upgrade this time round with `conda update atoti atoti-jupyterlab`.
But atoti-aws is not upgraded. So this means that going forward, we must upgrade each plugin manually?

```
atoti                     0.5.1                   7f32d5e    https://conda.atoti.io
atoti-aws                 0.5.0                    pypi_0    pypi
atoti-jupyterlab          0.5.1                   7f32d5e    https://conda.atoti.io
```

**Comment by tibdex** [comment]
It looks like you installed `atoti-aws` with `pip install atoti-aws` and not `conda`. That would explain why Conda isn't able to see that it should be updated too.
