### ISSUE TITLE
Error in browser console - 404 not found because duplicated proxy in url

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#232]
## Steps to reproduce

On a local JupyterLab, the console shows 404 (Not found) because the URL has proxy. However the second retry on localhost works, hence visualization is working fine.
![image](https://user-images.githubusercontent.com/35210495/106833848-4661a580-66cf-11eb-86f3-30c895635fda.png)

On a docker running locally, I get similar error. Visualization works fine in this case as well.
![image](https://user-images.githubusercontent.com/35210495/106835441-4fa04180-66d2-11eb-91bd-fba73c194d9b.png)

On a docker on AWS, the first rest call is on the correct IP but the duplicate proxy causes it to fail.
The second retry is on localhost and therefore it failed. Visualization shows waiting for connection.
![image](https://user-images.githubusercontent.com/35210495/106835536-752d4b00-66d2-11eb-890f-3dd696adf10a.png)

On docker with the env variable `BASE_URL` replaced, the visualization is still waiting for connection.
![image](https://user-images.githubusercontent.com/35210495/106835784-e7059480-66d2-11eb-90e2-e07ca818fffb.png)

## Environment

**Local**
- atoti: 0.5.1
- Operating System: win32

**AWS**
- atoti: 0.5.1
- Operating System: linux

**Comment by tibdex** [comment]
Hi Hui Fang, your last attempt with a Docker image deployed on AWS with the `BASE_URL` env variable set to `http://ec2co- ... .amazonaws.com` should work. In fact, we can see in the console that there was only a single `GET` request that failed (compared to two for the previous attempt where `BASE_URL` was not configured properly) so I guess the second `GET` request went through. Could you please also share the content of the _Network_ tab to see if it's really the case?

Anyway, since the UI got stuck on "Waiting for connection" there must be a problem somewhere but it would be good to know when/where the issue begins.

**Comment by HuifangYeo** [comment]
Hi @tibdex, yes you are right, visualization worked for the last attempt. 
This is the network traffic for the last attempt (I set BASE_URL to be the address of the load balancer)
![image](https://user-images.githubusercontent.com/35210495/106998485-8acc6e80-67bf-11eb-9bf9-2a32cfcfa8e5.png)

**Comment by HuifangYeo** [comment]
This is without overriding BASE_URL.
![image](https://user-images.githubusercontent.com/35210495/106999191-b7cd5100-67c0-11eb-9370-bc805d22bd1f.png)

The second try with http://localhost:8888/proxy/37987/versions/rest encounters COR problem. 
![image](https://user-images.githubusercontent.com/35210495/106999211-bef45f00-67c0-11eb-806d-c4d6c533bb99.png)

Ideally, the first try should be using `http://13.212.113.192:8888/proxy/37987/versions/rest` instead of `http://13.212.113.192:8888/proxy/37987/proxy/37987/versions/rest`.

**Comment by tibdex** [comment]
> Hi @tibdex, yes you are right, visualization worked for the last attempt.

I thought you said it didn't in your first message, saying it got stuck on "Waiting for connection".

> Ideally, the first try should be using http://13.212.113.192:8888/proxy/37987/versions/rest instead of http://13.212.113.192:8888/proxy/37987/proxy/37987/versions/rest.

Yes we could detect the presence of `/proxy/` in the URL and not add another one but you can imagine edge cases where the URL has `/proxy/` in it but it's not due to Jupyter Server Proxy but some other proxy in place and thus we would still need to try adding another `/proxy/`.

> without overriding BASE_URL

It's not a good practice to keep `BASE_URL` unchanged when deploying on the cloud because it makes `session.url` incorrrect/unusable.

**Comment by HuifangYeo** [comment]
Noted. I'll set `base_url` with the load balancer DNS.

Just a note: tried using https://checkip.amazonaws.com to get the IP address assigned to the docker container on AWS. However it returns the private IP instead.
