### ISSUE TITLE
Transformation of 3D and 4D arrays into a 2D format compatible with read_numpy in atoti

### ISSUE THREAD

**Issue by annegruz** [atoti/atoti#237]
## Description

Hello,
In my code I have 4D structures with results that I would like to send to atoti. I first need to reshape the structure to transform into a long format that can be sent to atoti. Could this step be packaged via Numpy to atoti functions?

You can find below an example with a notebook. First I create a 4D structure. Then I reshape into a 2D structure.

## Context
This is for computation of unexpected losses in a climate-extended credit model.

## Other information (if relevant)

[Lab.zip](https://github.com/atoti/atoti/files/5964408/Lab.zip)

Thank you,
Green RWA

**Comment by Skyscimitar** [comment]
Hello,

atoti is more of an analytics plateform and aggregation engine than a scientific computing and data wrangling library like NumPy. So functions like the ones you are using aren't part of atoti's feature set.

It is intentional that data transformation be done outside of atoti, in order to keep our API simple and targeted at what it does best.
