### ISSUE TITLE
Need clarification on all the read and load functions

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#241]
## Description
Hello, I am lost between all the load functions provided by atoti, could you please help me to understand this?

1) There is a read function for csv, numpy, pandas, parquet, spark and sql.
2) There is a load function for csv, pandas from a scenario.
3) There is a load function for csv, pandas from a simulation.
4) There is a load function for csv, kafka, pandas, parquet, spark and sql from a store.
5) And there is a load function for csv from a store scenarios.

What does it mean?
2+3) Scenarios and simulations can be uploaded by CSV or pandas files?
4) For CSV, doc says **Load a CSV into this scenario**, for Kafka it says **Consume a Kafka topic and stream its records in the store**.
3+5) The docs same the same thing **Load a CSV into this simulation** ; why? Moreover, in a case, the function comes from StoreScenarios and the doc is about simulation. Both are distinguished in points 2 and 3 however.
1+4) Why no read function for kafka? And why no load function for numpy?

**Comment by Skyscimitar** [comment]
Hi Harold,

> Why no load function for numpy?

This is an omission on our part, we will add it!

> Scenarios and simulations can be uploaded by CSV or pandas files?

There might be some confusion here about simulation's and scenarios. As you know, there are two kinds of simulation in atoti, source and measure, both of these simulations have scenarios. The [`store.scenarios["scenario"]`](https://docs.atoti.io/latest/lib/atoti.html#atoti.store.Store.scenarios) allows you to switch between scenarios of the source simulation (equivalent of AP branches). Calling `load_csv` on a scenario of a store loads data into the corresponding scenario (by default the `master` scenario is used). Measure simulations also have scenarios, however these are not handled by branches, but by a column in the simulation store. You can feed the measure simulation store with a pandas or a CSV file by using `load_csv` on the simulation object.

> There is a load function for CV from a store scenarios.

This function allows you to generate scenarios from the directory structure (we can only infer this properly with CSV files, which is why the only method allowing this is `load_csv`. Since this feeds multiple scenarios, the method is on the `StoreScenarios` object and not the store itself.

> Why no read function for kafka? For kafka it says consume a kafka topic and stream its records in the store?

Kafka is a real time message broker, the messages are not sufficient to parse the store schema. Since the `read_*` methods create the store it is not possible to do the same with a kafka source. You need to call `tt.create_store` first and then feed the store with the Kafka topic by calling the `load_kafka` method on the store. Like the other `load_*` methods, it loads the data into the selected scenario (or all of them if you use the `in_all_scenarios` parameter in the load function).

Hopefully this clarifies the behavior of the different `load/read` functions available, if you want more details on one of the points don't hesitate to ask.

**Comment by Harold7665** [comment]
Thanks a lot @Skyscimitar! This is clear :)
