### ISSUE TITLE
File used for Source Simulation is erased after kernel restart

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#253]
## Steps to reproduce

[issue-whatif.zip](https://github.com/atoti/atoti/files/6141799/issue-whatif.zip)

0. Run the notebook attached
1. Open ActiveUI
2. Open the source simulation tab
3. Drag'n drop the file new.csv
4. Add it as a new scenario (any name will do)
5. Click on "Upload file to scenario"
6. Then go back to the notebook. Restart the kernel
7. The file new.csv will be removed

## Actual Result
The file used for simulation is removed

## Expected Result
The file used for simulation shouldn't be removed

## Environment

- atoti: 0.5.2
- Python: 3.9.2
- Operating System: win32

## Logs (if relevant)
Gif to show what is happening:
![file_is_removed](https://user-images.githubusercontent.com/42935528/111164171-c6393480-85d8-11eb-9f15-ca26113a59e2.gif)

**Comment by Skyscimitar** [comment]
Hi Xavier,

When you upload  a file via the simulations UI, atoti creates a temporary copy of it from which it loads the data. It would seem that in your case, the temporary file is replacing the original  (if you watch carefully on the GIF, the moment you upload the file, the `last modified` date on your file changes from `4 minutes ago` to `seconds ago`). The file created by the server being temporary, it is deleted when the session is restarted. However since it took the place of the original file you are left with nothing.

Should be an easy fix, but until it's merged you should be able to avoid loosing the original file by putting it in a sub directory.

**Comment by xpilasav** [comment]
Thank you, the fix is good enough for the moment
