### ISSUE TITLE
[Session Config] - URL Pattern / Port (comfort)

### ISSUE THREAD

**Issue by NickFillot** [atoti/atoti#260]
## Description

Specify fixed port in config from url_pattern

**Python script**: _local_session.py

**Code**:
```
class LocalSession(BaseSession[_LocalCubes]):
    def __init__(
        self,
        name: str,
        config: SessionConfiguration,
        distributed: bool = False,
        **kwargs: Any,
    ):
        """Init."""
        self._name = name
        self._config = config

        self._create_subprocess_and_java_api(
            distributed,
            **kwargs,
        )

        try:
            self._configure_session()
        except AtotiJavaException as ave:
            # Raise an exception if the session configuration fails
            raise AtotiException(
                f"{ave.java_traceback}\n"
                f"An error occured while configuring the session.\n"
                f"The logs are availbe at {self.logs_path}"
            ) from None

        self._closed = False

    def _create_subprocess_and_java_api(
        self,
        distributed: bool,
        **kwargs: Any,
    ):
        py4j_java_port: Port
        if kwargs.get("detached_process", False):
            py4j_java_port = Port(_PY4J_DEFAULT_PORT)
            self._server_subprocess = None
            logging.getLogger("atoti.process").warning(
                "detached_process is True, expecting a running server with Py4J listening on port %d",
                py4j_java_port,
            )
        else:
            self._server_subprocess = ServerSubprocess(
                port=Port(self._config.port) if self._config.port else None,
                url_pattern=self._config.url_pattern,
                max_memory=self._config.max_memory,
                java_args=self._config.java_args,
                extra_jars=self._config.extra_jars,
                **kwargs,
            )
            py4j_java_port = self._server_subprocess.py4j_java_port
        self._java_api: JavaApi = JavaApi(
            py4j_java_port=py4j_java_port, distributed=distributed
        )
```

Maybe try to infer port from url_pattern given first (lower performance) or indicate to specify port in config documentation next to url_pattern

```
url_pattern = "http://{host}:8088"
try:
    self._config.port = int(url_pattern.split(':')[-1])
except:
    pass
```

Regards
Nicolas

**Comment by bloussou** [comment]
Hello @NickFillot,
Thanks for reporting this issue. It's a bug I come back to you when it is fixed.
As you described the workaround yet is to set the port both the the `url_pattern` and `port` arguments of the session configuration.

**Comment by tibdex** [comment]
Hello 👋🏻 ,

The docs could indeed be improved but these two config parameters are supposed to be used like this:
- `port` sets the port on which the atoti server will listen.
  It defaults to one of the currently available ports on your machine. The goal is to be able to start multiple sessions without having to care about port conflicts.
  When you want more stability/reproducibility (i.e. in production), you might want to pin the `port` to a specific value (e.g. 9090) so that the session is always accessible at the same URL.
- `url_pattern` is used when the atoti session is started from a distant VM / Docker container.
  It defaults to `{protocol}://localhost:{port}` which works well on your local machine because `{protocol}` will be replaced by the current one (probably HTTP) and `{port}` will be replaced by the port on which the atoti server listens (even when the `port` parameter is not passed).
  However, when atoti is started from a Jupyter instance hosted on the cloud, `{protocol}://localhost:{port}` won't be the right URL. Indeed, your browser won't be able to reach the atoti session because it's in the cloud and not on your `localhost`.
  That's where [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy) can be useful. For example, if your Jupyter instance is available at `https://project.cloud.provider:8080`, you can set `url_pattern` to `https://project.cloud.provider:8080/proxy/{port}` and `session.url` will indeed let you access the session from your browser.
  Sometimes, the network setup is more complicated and the port used by the atoti session on the VM is not even part of the public URL from which it can be accessed. That's why `url_pattern` offers full control on how the URL will look like.

Inferring the port from `url_pattern` and forwarding it to the `port` parameter would thus work in some cases but not all. Cases where this mechanism stops to work would be very confusing so we prefer to not infer anything and let the user pass both the `port` and `url_pattern` when needed.
