### ISSUE TITLE
Required levels issue when creating a multilevel hierarchy

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#312]
## Steps to reproduce

While trying a use case for a client, playing with joining new tables afterwards and creating new measures, I noticed this behaviour. Not entirely a bug but it leads to issue of understanding some behaviours.

```python
import atoti as tt
import pandas as pd
session = tt.create_session()
table_1 = session.read_pandas(
    pd.DataFrame({
        "A": ["a1", "a2", "a3", "a4"],
        "B": ["b1", "b2", "b1", "b2"],
        "C": ["c1", "c1", "c1", "c1"],
        "m1": [10.0, 20.0, 30.0, 40.0]
    }),
    keys=["A"],
    table_name="table_1"
)
cube = session.create_cube(table_1, mode="no_measures")
m, lvl, h = cube.measures, cube.levels, cube.hierarchies
m["m1.VALUE"] = tt.value(table_1["m1"])
print(m["m1.VALUE"]._required_levels)
# >>> ['A@A@table_1']
h["Test"] = [lvl["C"], lvl["B"], lvl["A"]]
m["m1.VALUEBIS"] = tt.value(table_1["m1"])
# m1.VALUEBIS and m1.VALUE don't have the same required levels, it created an issue as how to understand behaviours of some measures.
print(m["m1.VALUEBIS"]._required_levels)
# >>> ['A@Test@table_1', 'A@A@table_1']
```

## Environment

- atoti: 0.6.0.20210702091122
- Python: 3.9.5
- Operating System: win32

**Comment by Skyscimitar** [comment]
![requiredlevels](https://user-images.githubusercontent.com/24211435/124490661-abbadf00-ddb2-11eb-8b76-356b3ed6424c.png)

The value measure automatically adds all the levels which correspond to key fields of the table to a value measure's required levels. As you can see in the screenshot, the `m1.VALUEBIS` measure has no value unless both `lvl[("A", "A")` and `lvl[("Test", "A")` are defined.

We could select one of the levels (say the first one) to determine the measure's required levels but I don't think this would make the behavior any clearer. For example, if only `lvl[("A", "A")` is used, both measures have no value if only `lvl[("Test", "A")` is defined. In the use case you gave in the example, since the user just defined a multilevel hierarchy, it would be odd for the measure not to have a value on it.

In my opinion, the safest, and most consistent way, of building value measures would be to raise an exception if multiple levels correspond to the key fields of the table, and require that the user specify a level (in this case `m["m1.VALUEBIS"] = tt.value(table_1["m1"], levels=[lvl[("Test, "A")]]`), the matching levels would be obviously be specified in the exception message to help the user define their measure.

**Comment by alexis-bvq** [comment]
I agree with you on the warning idea.
Once you created a measure who has the required_level on lvl[("A", "A")], you can't delete this level even though it still "exist" under lvl[("Test", "A")] and the error message is not great.

Here it is fine :
```
import atoti as tt
import pandas as pd
session = tt.create_session()
table_1 = session.read_pandas(
    pd.DataFrame({
        "A": ["a1", "a2", "a3", "a4"],
        "B": ["b1", "b2", "b1", "b2"],
        "C": ["c1", "c1", "c1", "c1"],
        "m1": [10.0, 20.0, 30.0, 40.0]
    }),
    keys=["A"],
    table_name="table_1"
)
cube = session.create_cube(table_1, mode="no_measures")
m, lvl, h = cube.measures, cube.levels, cube.hierarchies
h["Test"] = [lvl["C"], lvl["B"], lvl["A"]]
# m["m1.VALUE"] = tt.value(table_1["m1"])
del cube.levels[("table_1", "A", "A")]
```

Here it is not fine :
```
import atoti as tt
import pandas as pd
session = tt.create_session()
table_1 = session.read_pandas(
    pd.DataFrame({
        "A": ["a1", "a2", "a3", "a4"],
        "B": ["b1", "b2", "b1", "b2"],
        "C": ["c1", "c1", "c1", "c1"],
        "m1": [10.0, 20.0, 30.0, 40.0]
    }),
    keys=["A"],
    table_name="table_1"
)
cube = session.create_cube(table_1, mode="no_measures")
m, lvl, h = cube.measures, cube.levels, cube.hierarchies
h["Test"] = [lvl["C"], lvl["B"], lvl["A"]]
m["m1.VALUE"] = tt.value(table_1["m1"])
del cube.levels[("table_1", "A", "A")]
```

**Comment by bloussou** [comment]
Hello, this will be added in the next release

**Comment by bloussou** [comment]
Hello,
required levels concept has been removed in atoti `0.7.0` along with the deprecation of `tt.value()` function. Now you should use [`tt.agg.single_value()`](https://docs.atoti.io/latest/lib/atoti/atoti.agg.single_value.html#atoti.agg.single_value). So I think we can consider this as "fixed".

@alexis-bvq if you agree feel free to close this issue.
