### ISSUE TITLE
Missing change java_args to java_options

### ISSUE THREAD

**Issue by Harold7665** [atoti/atoti#328]
# Description
As specified in the title, this change is not listed in the 0.6.0 Changelog.

**Comment by tibdex** [comment]
Hi,

The changelog mentions:

> create_session()’s config parameter expects a plain Python object following the structure of SessionConfig rather than an object created with config.create_config() or a path to a config file.

It doesn't say that the structure of the `SessionConfig` is the same as the one that was passed to `create_config()`. In fact, `java_args` -> `java_options` is not the only change.

`metadata_db` -> `user_content_storage` only got a dedicated bullet point because it implied more changes from the user than just restructuring the given config.

**Comment by rcolle** [comment]
I agree that we should however list all the changes in the changelog to ease the migration.

**Comment by bloussou** [comment]
Hi, this will be available in the next release.
