### ISSUE TITLE
Visualization in previous cell broke when hierarchy is sliced

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#334]
## Steps to reproduce

I have a visualization in a notebook that uses the date hierarchy.
![image](https://user-images.githubusercontent.com/35210495/128821662-e5ea9859-5d2b-4bce-aa96-b45ef3c0f5d4.png)

Upon slicing the hierarchy in a later cell, the visualization broke without any interaction.
![slicing](https://user-images.githubusercontent.com/35210495/128822305-24301ef3-8cf9-478b-a625-f47134f072c8.gif)

Theoretically, actions in cells later in the notebook shouldn't impact earlier cells unless the earlier cell gets re-executed.

## Environment

- atoti: 0.6.0
- Operating System: win32

**Comment by tibdex** [comment]
> Theoretically, actions in cells later in the notebook shouldn't impact earlier cells unless the earlier cell gets re-executed.

I agree. This is also what happens most of the time.

However, you still want the content of the sidebar to be aware of the data model changes so that it displays an up-to-date structure that the user can reliably work with. You also want the widget to be aware of these changes since. Indeed, in an upcoming release, it will be possible to expand a pivot table cell by another hierarchy by clicking on a new context menu item that will then open a hierarchy picker. Here too, the hierarchy picker will have to display the up-to-date data model.

Ideally, we would thus like the widget and the sidebar to be aware of data model changes but not actually rerender themselves until the notebook cell is re-executed. Indeed, since the cell execution is a user intervention, it's OK if the rendering of a widget (and its sidebar) built with an outdated data model goes wrong. Same thing happens with regular notebook cells when the variables they reference have changed to something incompatible.

**Comment by tibdex** [comment]
The solution described above cannot be cleanly implemented at the moment with the way the underlying UI library listens to data model changes so I'm postponing its resolution.

A workaround would be to save the notebook and refresh the browser tab as this will snapshot the widgets which will thus stop listening to data model changes.
