### ISSUE TITLE
create_parameter_simulation with multiple measures failed with unclear message

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#340]
## Steps to reproduce
Initially I created the simulation with `points` defaulted to `None`: 
```
pointssystem_sim = f1cube.create_parameter_simulation(
    "pointssystem_sim4",
    measures={"Best results": 1000, "points": None},
    levels=[l["positionText"], l["resultId"]],
)
```
However, an error was thrown. Hence I retried by setting the default value to `-1`. It still throw an error as follows:
![image](https://user-images.githubusercontent.com/35210495/130547871-660bea09-31d5-430f-8b11-1a94468cb2ca.png)

I don't observe any obvious error in the server.log. However, if I renamed `points` to `y` with default value `-1`, I can create the simulation successfully. **Default `None` also worked when the measure name is not `points`.**

```
pointssystem_sim = f1cube.create_parameter_simulation(
    "pointssystem_sim4",
    measures={"Best results": 1000, "pointsx": None},
    levels=[l["positionText"], l["resultId"]],
)
```

[main.zip](https://github.com/atoti/atoti/files/7036163/main.zip)

## Environment
- atoti: 0.6.1
- Python: 3.9.6
- Operating System: win32

## Logs (if relevant)
[server.log](https://github.com/atoti/atoti/files/7036136/server.log)

**Comment by Skyscimitar** [comment]
Hi, the error occurs because another table contains a column with the name `points`, atoti wrongly tries to create a reference between the column in the simulation table with the same name as the measure and the existing one, which inevitably creates problems.

This will be fixed in the next release, in the mean time choosing unique measure names should solver the issue.
