### ISSUE TITLE
Confusing contributors.COUNT with one-to-many join

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#35]
## Steps to reproduce

Datasets:
```python
import pandas as pd

matches = {
    "match_id": [0, 1, 2, 3],
    "Day": [1, 1, 2, 2],
    "Home": ["Liverpool", "Norwich", "West Ham", "Everton"],
    "Away": ["West Ham", "Everton", "Liverpool", "Norwich"],
}
matches_df = pd.DataFrame(data=matches)

goals = {
    "goal_id": [0, 1, 2, 3],
    "match_id": [0, 0, 0, 3],
    "Team": ["Liverpool", "Liverpool", "West Ham", "Everton"],
}
goals_df = pd.DataFrame(data=goals)
```

Create cube:
```python
import atoti

session = atoti.create_session()

matches_store = session.read_pandas(matches_df, keys=["match_id"])
goals_store = session.read_pandas(goals_df, keys=["goal_id"])
matches_store.join(goals_store, mapping={"match_id": "match_id"})

matches_cube = session.create_cube(matches_store, "MatchesCube")
```

![image](https://user-images.githubusercontent.com/4415696/81820434-e7e90b80-9530-11ea-95ab-27ea14435437.png)

Define measures:
```python
m = matches_cube.measures
level = matches_cube.levels
h = matches_cube.hierarchies

m["Goal.DISTINCT_COUNT"] = atoti.agg.count_distinct(goals_store["goal_id"])
m["Goal.COUNT"] = atoti.agg._count(goals_store["goal_id"])
m["Match.DISTINCT_COUNT"] = atoti.agg.count_distinct(matches_store["match_id"])
m["Match.COUNT"] = atoti.agg._count(matches_store["match_id"])
```

## Actual Result

Total `contributors.COUNT` is 4, one per match id:
![image](https://user-images.githubusercontent.com/4415696/81821090-bfaddc80-9531-11ea-90f1-0cacf1d4176c.png)

If we crossjoin by goal id, we still get 4 but the count does NOT add up:
![image](https://user-images.githubusercontent.com/4415696/81821199-df450500-9531-11ea-8e88-3f1f86e1610e.png)

If we add the measures aggregating goals:
- `Goal.DISTINCT_COUNT` is correctly equal to 4
- `contributors.COUNT` changed to 10 and does not add up (?)
- `Goal.COUNT` is equal to 11 and does not add up (?)

![image](https://user-images.githubusercontent.com/4415696/81822044-e9b3ce80-9532-11ea-8ab4-999ccffc4c1e.png)

## Expected Result

I would expect more documentation in the cases of one-to many join in this page for example https://docs.atoti.io/0.3.1/tutorial/04-advanced-store-manipulations.html#Join-stores

In particular:
1. What is `contributors.COUNT` supposed to be?
   1. Is it "How many facts are in the main store"?
   1. Should we rename it `BaseStore.COUNT`?
   1. The fact that `contributors.COUNT` does not add up is confusing.
   1. The fact that `contributors.COUNT` changes when adding the measure on the secondary store is confusing as well. What do these values represent?
1. How do I get the count of secondary stores?
   1. Is `atoti.agg._count(goals_store['goal_id'])` a valid usage? If that's the case we may want to make it public and remove the leading `_`.
   1. The fact that `Goal.COUNT` does not add up is confusing.
   1. What does 11 represent here for `Goal.COUNT`?
1. [I would personally expect the join to behave like a LEFT JOIN](https://github.com/atoti/atoti/issues/36) and the count to be 6. See the SQL example below:

```sql
CREATE TABLE match_store (
	match_id int,
  	Day int,
  	Home varchar(255),
  	Away varchar(255)
);
CREATE TABLE goal_store (
	goal_id int,
	match_id int,
  	Team varchar(255)
);
INSERT INTO goal_store
VALUES
	(0,0,"Liverpool"),
	(1,0,"Liverpool"),
	(2,0,"West Ham"),
	(3,3,"Everton");
INSERT INTO match_store
VALUES
	(0,1,"Liverpool", "West Ham"),
	(1,1,"Norwich", "Everton"),
	(2,2,"West Ham", "Liverpool"),
	(3,2,"Everton", "Norwhich");
```

Inner join:
```sql
SELECT * from match_store INNER join goal_store on match_store.match_id=goal_store.match_id
```
![image](https://user-images.githubusercontent.com/4415696/81827464-0fdc6d00-9539-11ea-86a4-5fbf1cde5154.png)

Left join:
```sql
SELECT * from match_store LEFT join goal_store on match_store.match_id=goal_store.match_id
```
![image](https://user-images.githubusercontent.com/4415696/81827541-25519700-9539-11ea-827e-ccbeda3a1db1.png)

## Environment

- Atoti: 0.4.0.20200511082531
- Python: 3.8.2
- Operating System: linux

**Comment by a-manai** [comment]
Hi Julien,

This issue is about joins (in particular one-to-many and many-to-many joins) and the COUNT measure.
We have been working on those things in the past months, and here are the changes that will be made available in the next release:
- all atoti joins are now LEFT joins. There was an inconsistency where one-to-one and many-to-one joins were of type LEFT and other joins were INNER joins. As a result, now, you will also see rows for the default value of the target store when there is no match:
![Screenshot_2020-11-20 JupyterLab(3)](https://user-images.githubusercontent.com/29857152/99814973-023c1b80-2b4a-11eb-9c95-3617978bd444.png)


- the `Contributors.COUNT` measure now behaves like other measures, and in particular follows the rule that **a measure must have a unique value on a given location** in the pivot table (that was not the case because the count value of the grand total changed following whether _goal_id_ was also in the query)

What has not changed is that a cube in atoti is tied to a base store. Its `contributors.COUNT` measure represents **the number of rows in the base store matching a given location** in a pivot table (a set of coordinates on the levels). Whether it should be renamed `BaseStore.COUNT` is currently being discussed.
As a result, here is the current result of that query:
![Screenshot_2020-11-20 JupyterLab(1)](https://user-images.githubusercontent.com/29857152/99813391-e6d01100-2b47-11eb-9258-5435e3342555.png)
As you can see, the count doesn't add up in the _goal_id_ hierarchy (which comes from a one-to-many join) but it does in the _match_id_ one.

Finally, counting rows can be a bit unintuitive since everything is related to the base store; this is why `_count` is hidden. We also found (also thanks to this issue) some bugs in the `COUNT` function, hence why it still has a more advanced/experimental status than other aggregations.
In general you will probably get what you expect in those more complex situations with the `count_distinct` function. May I ask more about a real-life use case?

**Comment by jbe456** [comment]
Thanks for the update. Looking forward to it.

>May I ask more about a real-life use case?

I used the `_count` aggregation function typically because I wanted the count to add up when expanding against certain hierarchies. In particular if the "regular count" is in fact a base store count, it could prove useful. If we encounter again such a need I can always create a new ticket with more context.

BTW some of the details provided in your answer should be mentioned in the doc, very useful to understand the nitty-gritty!
