### ISSUE TITLE
Issue filtering on a non slicing parameter hierarchy

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#416]
## Steps to reproduce
```python
import atoti as tt
import pandas as pd
session=tt.create_session()
table = session.read_pandas(pd.DataFrame(
        [
            ["A", [1,2,3]],
            ["B", [4,5,6]]
        ],
        columns=["l1", "m1"]
    ), 
    table_name="table"
)
cube = session.create_cube(table)
m, l = cube.measures, cube.levels
cube.create_parameter_hierarchy_from_members("l2", [0,1,2])
m["m1_sum"] = tt.agg.sum(table["m1"])
m["m1_expand"] = m["m1_sum"][l["l2"]]
# By default l2 is slicing and it is working.
cube.query(m["m1_expand"], condition=l["l2"] == "1")
h = cube.hierarchies
h["l2"].slicing = False
# Now that l2 is not slicing it is not working anymore
cube.query(m["m1_expand"], condition=l["l2"] == "1")
```

## Environment

- atoti: 0.6.2
- Python: 3.9.6
- Operating System: win32

**Comment by fabiencelier** [comment]
I have seen the same issue while working on thunder

This can even be reproduced with the count:

```python
import atoti as tt
import pandas as pd
session = tt.create_session()
df = pd.DataFrame(
    {
        "Seller": ["Seller_1", "Seller_1", "Seller_2", "Seller_2"],
        "ProductId": ["aBk3", "ceJ4", "aBk3", "ceJ4"],
        "Price": [2.5, 49.99, 3.0, 54.99],
    }
)

table = session.read_pandas(df, table_name="Seller")
cube = session.create_cube(table)
l, h, m = cube.levels, cube.hierarchies, cube.measures
cube.create_parameter_hierarchy_from_column("Competitor", table["Seller"])
```
```python
cube.query(m["contributors.COUNT"], levels=[l["Competitor"]])
```
![Screenshot from 2021-11-22 15-55-07](https://user-images.githubusercontent.com/17087544/142883215-f7c866ab-b60f-40c6-b989-764610645065.png)

```python
h["Competitor"].slicing = False
cube.query(m["contributors.COUNT"], levels=[l["Competitor"]])
```
![Screenshot from 2021-11-22 15-55-31](https://user-images.githubusercontent.com/17087544/142883247-f4a9cb94-f119-4578-b8f2-e18d8c12011e.png)

**Comment by rcolle** [comment]
These are 2 different issues.

In @alexis-bvq 's case, the issue is simply that the measure is doing an array expansion: when the hierarchy becomes non-slicing, the default member is "AllMember", and the array cannot be expanded on the "AllMember" coordinate.
Running the following query works:
```
cube.query(m["m1_expand"], levels=[l["l2"]], condition=l["l2"] == "1")
```

In @fabiencelier 's case, the issue is that by default, an analysis hierarchy only exposes data by replicating it on its first level: the "Competitor" level when slicing, and the ALL level when non-slicing.
The analysis hierarchy needs to be explicitly handled by a measure for it to have values on its following (all but first) levels.

**Comment by alexis-bvq** [comment]
Even though there is a way to avoid the issue, should we at least throw a better error message ?

**Comment by rcolle** [comment]
> Even though there is a way to avoid the issue, should we at least throw a better error message ?

Is there any error message? I thought we were simply displaying no values.

Would you like an error message? What would you like it to be and in which case?

There are use-cases where people add an ALL level to an array expansion hierarchy so that they can display an "aggregated value". For instance in the case of an exposure array based on monte-carlo simulations, I've seen an ALL level used to display the PFE while the underlying "index" level is used to display the individual exposures.
