### ISSUE TITLE
where condition + hierarchy creation inconsistencies

### ISSUE THREAD

**Issue by xpilasav** [atoti/atoti#456]
## Steps to reproduce

Run the notebook below and see the differences between:

- V1 and V2: doing the same computation but using the same data in two ways of creating a hierarchy gives us a different outcome
- Where condition in both V1 and V2: we try to do measure=constant, level=constant and level=measure and we don't have the same results

[notebook.zip](https://github.com/atoti/atoti/files/7888253/notebook.zip)

## Actual Result

See the pivot tables in the notebook

## Expected Result

Everything to be consistent

## Environment

- atoti: 0.6.4
- Python: 3.10.2
- Operating system: win32

## Logs (if relevant)
N/A

**Comment by Acriss** [comment]
Hi Xavier,

Coming back with some information regarding the first case (Product V1).
First of all, when calling `cube.create_parameter_hierarchy_from_column("strike v1", products_table["strike"])`, you create a special type of hierarchy that is a [factless hierarchy](https://www.activeviam.com/activepivot/latest/docs/concepts/dimensions_and_hierarchies/#factless-hierarchies).
You then create a hierarchy that is composed of some of the initial levels, and the `strike v1` that was just created. Seems that at this point, since the strike level comes from the base store anyway, we end up with a regular axis hierarchy. (**to confirm**)

Now with the issue with Product V1, we have `tt.agg.sum(tt.where(m['Parent strike min to 1 v1'] == 9515, m["Historical VaR 95%"], 0), scope=tt.scope.origin(lvl[("Products", 'Product v1', 'strike v1')]))` that yields values for locations where `m['Parent strike min to 1 v1']`.

Your notebook states:
One with a where between a level and a constant = OK
One with a where between a measure and a constant = FAIL
One with a where between a level and a measure = OK
Now that I think about it, I have to disagree: `where between measure and 9515` works, because the measure used is `Parent strike min to 1 v1` which value is always 9515, so they are equal for all locations. Am I wrong ?
If I am right though, that means that "One with a where between a level and a measure" is actually Failing, because the measure `Parent strike min to 1 v1` is always 9515, but the level's members aren't.

**Comment by xpilasav** [comment]
"Now that I think about it, I have to disagree: where between measure and 9515 works, because the measure used is Parent strike min to 1 v1 which value is always 9515, so they are equal for all locations. Am I wrong ?"
I get it: yes, I should use m['strike with min to 1 v1'] instead of the Parent value
That explains the case V1
BUT
If you change m['Parent strike min to 1 v1'] to m['strike with min to 1 v1'] in line THREE, it doesn't work... Why is that ?

**Comment by Acriss** [comment]
Because you shouldn't change it:
You want to have values where the equality between the members of a level is equal to the evaluation of a measure at this location. But all the while, you want it only for the value 9515. So in this case, you need the parent value, else, the two are equals everywhere. So you see non zero values everywhere.

**Comment by xpilasav** [comment]
Make sense. Thank you !
I changed on my notebook and all works OK for the case V1.
Do we have something on the case V2 ?

**Comment by Acriss** [comment]
Same thing for V2, if you use 
```diff
- m['Portfolio Ref 1 Eq to Measure v2'] = tt.agg.sum(tt.where(m['Parent strike min to 1 v2'] == 9515, m["Historical VaR 95%"], 0), scope=tt.scope.origin(lvl[("Products", 'Product v2', 'strike v2')]))
+ m['Portfolio Ref 1 Eq to Measure v2'] = tt.agg.sum(tt.where(m['strike with min to 1 v2'] == 9515, m["Historical VaR 95%"], 0), scope=tt.scope.origin(lvl[("Products", 'Product v2', 'strike v2')]))

```

**Comment by xpilasav** [comment]
m['Portfolio Ref 1 Eq to Measure v2'] was already working 
The issue was on m['Portfolio Ref 1 Measure Eq To Level v2'] and it's not working with both 'Parent...' and 'strike...'

**Comment by Acriss** [comment]
The reason for that was a difference in scope definition:
```diff
- scope=tt.scope.origin(lvl[("Products", 'Product v1', 'strike v1')])
+ scope=tt.scope.origin(lvl[("Products", 'strike v2', 'strike')])
 ```
It should be `scope=tt.scope.origin(lvl[("Products", 'Product v2', 'strike')])` if you want the comparison to be relevant.

To prevent having this kind of mistake, you'd need to drop the hierarchies that you don't need anymore : 
![image](https://user-images.githubusercontent.com/26595733/150758941-c5b5e817-ada0-4f23-a1f4-304ffbf41598.png)

```python
h.pop('strike v1')
h.pop('strike v2')
h.pop('optionType')
h.pop('prod')
h.pop('maturity')
```

**Comment by xpilasav** [comment]
scope=tt.scope.origin(lvl[("Products", 'Product v2', 'strike')]) doesn't work in my notebook as it says KeyError: 'No level with name strike found in cube.'
Can you show me how you made it work ?

**Comment by Acriss** [comment]
This version of the notebook 
[Aurora project.zip](https://github.com/atoti/atoti/files/7932210/Aurora.project.zip)

**Comment by xpilasav** [comment]
All good, got my mistake. Thanks @Acriss for the investigation
All makes sense

**Comment by rcolle** [comment]
> Seems that at this point, since the strike level comes from the base store anyway, we end up with a regular axis hierarchy. (**to confirm**)

It looks like there's a bug / problem here. While `strike v1` is on its own in a single level hierarchy, it behaves as expected and replicated data as an analysis hierarchy.
However, once it becomes part of a multi-level hierarchy, it behaves like a regular hierarchy and relies on fatcs.

**Comment by xpilasav** [comment]
Should we keep the ticket open ? Do you need another ticket ?
