### ISSUE TITLE
Ability to choose columns from CSV 

### ISSUE THREAD

**Issue by HuifangYeo** [atoti/atoti#462]
There are some instances when users only want a subset of the columns and they have to use Pandas to achieve this. E.g.:
```py
combat_df = pd.read_csv(
    "resources/combats.csv",
    header=0,
    names=[
        "Registration ID",
        "Combat ID",
        "Pokemon ID",
        "Opponent Pokemon ID",
        "Result",
        "Type Multiplier",
        "Replay Views",
        "Live Views (Start - End)",
    ],
)

combat_df.drop(columns=["Replay Views", "Live Views (Start - End)"], inplace=True)
```
Would it be easier if we have parameters in the `atoti.read_*` and `atoti.load_*` function to choose or drop columns? 
Then there is one less dependency used in the project if Pandas is used solely for this purpose.

**Comment by bloussou** [comment]
>  Then there is one less dependency used in the project if Pandas is used solely for this purpose.
I disagree with this, `pandas` is required by atoti since the objects returned when doing a query are `pandas.DataFrame` so pandas will always be here as a dependency when using atoti.

For the parameter I let @tibdex decide. We can imagine making `types` parameter strict and only loading columns defined in `types` if types is defined and the strtict mode chosen

**Comment by Acriss** [comment]
On the one hand, the use of pandas makes this easy , and most data scientists will instinctively know how to do this.
On the other hand, our underlying [csv source](https://www.activeviam.com/activepivot/latest/docs/sources/csv_source/#skipping-columns) can do this.
Memory-wise, it should be better not to materialize the columns.

**Comment by bloussou** [comment]
As a workaround you can create the table with `session.create_table` and then load your csv.

**Comment by tjj225** [comment]
@bloussou from a performance/memory point of view which is faster to do this use case? Pandas or AP CSV source, I am just curious.  If CSV source is better I think we should support this use case rather than depending on Pandas.

**Comment by HuifangYeo** [comment]
Hi @bloussou,

while I understand that Pandas is an existing dependency for atoti, as an end-user, I'll still have to import Pandas and perform additional clean-up. Whereas if we have a parameter that allows them to select/drop some columns, and manage it within our API, it will make the codes cleaner for end-users. 

Also, maybe I was thinking more of the AP CSV Source implementation where we could have prevented the data from being loaded fully in the first place. It's better than having a Pandas object in addition to having the cube.

**Comment by tibdex** [comment]
atoti doesn't focus on ETL since tools such as pandas already do it very well. That being said, I think ignoring or renaming columns from a CSV or Parquet file is really at the edge of ETL and that we should support it. This will provide better performance than having to go through pandas and it will work natively with [cloud storage](https://docs.atoti.io/0.6.4/data-access.html#cloud-object-stores).

An API that would be compatible with our underlying CSV and Parquet sources would be to add a `columns: Optional[Mapping[int, str]] = None` parameter to our `read/load_csv/parquet()` methods. Where the mapping keys are the indices of the file columns to read and the mapping values are the table column names. It would be used like this:

```py
# some.csv has the following structure:
#
#  id,price,year,name
#  1,20000,2022,car
#  2,600,2020,phone

table = session.read_csv(
  "some.csv",
   columns={3: "Name", 1: "Price"}
)
assert table.columns == ["Name", "Price"] # in that order
```

`read/load_pandas/sql/etc()` don't need this parameter since the input data can be efficiently edited before calling these methods.

**Comment by bloussou** [comment]
Don't you think we should have a `Mapping[str,str]` with csv column name -> atoti table column name ?
Not sure it is simple to count the column index
```python
# some.csv has the following structure:
#
#  id,price,year,name
#  1,20000,2022,car
#  2,600,2020,phone

table = session.read_csv(
  "some.csv",
   columns={"name": "Name", "price": "Price"}
)
```

**Comment by bloussou** [comment]
Hello,
Selection and the possibility to rename columns for parquet en csv file will be available in the next release.

**Comment by HuifangYeo** [comment]
Hi @bloussou,

just wanted to provide feedback on the new change. In v0.6.5, we can rename the column as shown below:

```
candidates_tt = session.read_csv(
    "data/2022/candidates.csv",
    columns={
        "": "candidate_id",
        "name": "name",
        "group": "group",
        "party": "party",
        "status": "status",
    },
    keys=["candidate_id"],
)
```
However, in this case, we also have to repeat all the other column names that need not be updated, otherwise, they will not be loaded into the table. In this case, there's a bit of code redundancy. Would it be cleaner to split renaming from column selection?

**Comment by bloussou** [comment]
Hi,
I don't think we want two ways to do the same thing, it is against the python rule [`There should be one-- and preferably only one --obvious way to do it.`](https://peps.python.org/pep-0020/#the-zen-of-python). We know it is a bit of redundancy but it is not something that should be written too often so I don't think it is too bad. What do you think @tibdex ?

**Comment by tibdex** [comment]
You could use this code if you want less redundancy and fewer things to type:

```python
candidates_tt = session.read_csv(
    "data/2022/candidates.csv",
    columns={
        "": "candidate_id",
        **{name: name for name in ["name", "group", "party", "status"]},
    },
    keys=["candidate_id"],
)
```
