### ISSUE TITLE
hierarchy's `visible` property is not taken into account in the UI

### ISSUE THREAD

**Issue by printhellohetal** [atoti/atoti#466]
## Steps to reproduce
Run through below in a jupyter notebook

```python
import atoti as tt
import pandas as pd

session = tt.create_session()

df = pd.DataFrame(
    columns=["A", "B", "C"],
    data=[
        ("A", "red", 150.0),
        ("B", "blue", 150.0),
        ("C", "red", 250.0),
        ("D", "red", 150.0),
    ],
)
visible = session.read_pandas(
    df,
    keys=["A"],
    table_name="visible_check"
)

cube = session.create_cube(visible)

h, l, m = cube.hierarchies, cube.levels, cube.measures

h["B"].visible # to verify it is currently set to true

m["C.MEAN"].visible = False
h["B"].visible = False

m # to check if m["C.MEAN"] is visible
h # to check if h["B"] is visible

h["B"].visible # to verify it is currently set to false

```
## Expected Result
Hierarchy is no longer visible

## Environment

- atoti: 0.6.4
- Python: 3.8.12
- Operating System: MacOS Monterey

**Comment by bloussou** [comment]
Indeed I can still see the hierarchy in the menu of `session.visualize()`

**Comment by Acriss** [comment]
Hi @printhellohetal ,
There are two issues here:
- The hierarchy still shows on the notebook's JSON representation of your hierarchies. I believe this can be fixed with a simple filter on our side, and I'll work on it.
- The hierarchy still shows on the UI. I've tracked this issue to what seems to be an error in the discovery REST service (the one that returns the list of cubes/dimensions/measures etc... to the UI). This is an issue in our dependencies, and I've opened an associated ticket.

Cheers,
Pierre

**Comment by Acriss** [comment]
Hello !
This will be fixed in the next release of atoti (0.6.5) !
Thanks for reporting the issue.
Cheers

**Comment by Acriss** [comment]
closes #246

**Comment by bloussou** [comment]
It is not working as expected : https://github.com/atoti/atoti/discussions/563

**Comment by bloussou** [comment]
After a check, hierarchy discovery contains the correct values :
```
 {'name': 'TradeId',
         'caption': 'TradeId',
         'slicing': False,
         'visible': False,
         'levels': [{'name': 'ALL', 'caption': 'ALL', 'type': 'ALL'},
          {'name': 'TradeId', 'caption': 'TradeId', 'type': 'REGULAR'}]}
```

**Comment by bloussou** [comment]
[Internal ticket](https://support.activeviam.com/jira/browse/UI-7228)
