### ISSUE TITLE
Improve cube.visualize()

### ISSUE THREAD

**Issue by alexis-bvq** [atoti/atoti#49]
## Description

An other way of doing cube.visualize() would be to do it directly from the code like this:
- cube.pivot(level=[...level_names], measures=[...measure_names], columns[...level_names], filters[...filters])
- cube.graph(level=[...level_names], measures=[...measure_names], columns[...level_names], filters[...filters], graph_type)
- feature_value(level=[...level_names], measures=[...measure_names], columns[...level_names], filters[...filters])
- tabular(level=[...level_names], measures=[...measure_names], columns[...level_names], filters[...filters])

Therefore you wouldn't have to go into the left bar.

## Context

When you are developing in the notebook your hands are on the keyboard because you are coding. When you want to test or see the result of a measure you've just coded, cube.visualize() is useful. However, first you have to chose which type of widget, and then you have to go into the left bar and find back the measures and relevant levels you just typed in your cell.
It would be nice to instead type cube.pivot(levels=[], columns=[], measures=[], filters=[]) or cube.graph(levels=[], columns=[], measures=[], filters=[], graph_type) and then you just have to grab (copy past) the relevant name from the cell you just coded.

**Comment by tibdex** [comment]
Hi Alexis, thanks for your suggestions.

While I believe we haven't reached the perfect UX / notebook feeling with the JupyterLab integration, I don't think what you describe would be an improvement.

- If you start declaring more things, such as levels, measures, and filters, about the query being visualized through code, then you would expect that the next time you execute the cell, it goes back to the state described by that code. So any manipulations (adding hierarchies, sorting, formatting, etc.) you would have done the previous time on your widget would get lost.
So, basically, if you start describing something in code, you freeze the widget, making the extension less useful for exploratory analysis. Unless of course, we start adding support for bi-directional manipulations (ala [bamboolib](https://bamboolib.8080labs.com/)) where manipulations done through the widget modify the code of the corresponding cell.
- The main value of the extension, is to allow users to explore their cubes interactively. If everything must be described with code, you slow the feedback loop down. 
Besides, `Cube.query()` already accepts Python objects for measures, levels and filters and returns a pandas DataDrame similar to what your `tabular()` suggestion would give. You could also easily turn this DataFrame into a chart with [Plotly Express](https://plotly.com/python/plotly-express/). 

Other ways I see of improving the extension:
- Take the bi-directional approach where the widget underlying JSON state would be moved from the cell metadata to the cell code source and kept in sync with manipulations done through the UI. This would probably require a cleaner/more minimal JSON state as the one we have today to not make the cell code look too scary.
- Allow the output of `Cube.query()` to be transformed into an interactive widget in a new cell below so that you could start from an existing query instead of re-creating it from scratch in the atoti sidebar.
- A mix of both where you always start from `Cube.query()` (no more `Cube.visualize()`), get a widget from that, and any manipulations done on the widget would change the Python objects passed as arguments to `Cube.query()`. While this sounds nice, it would be the hardest to implement.

**Comment by HuifangYeo** [comment]
Hi,
I would love to have this feature as well.

Looking at https://www.kaggle.com/pavanraj159/telecom-customer-churn-prediction#3.2 for instance, user can simply pass in different parameters in different iterations to generate multiple charts while we have to manually create it one by one.

**Comment by tibdex** [comment]
> first you have to chose which type of widget

Since atoti 0.5.0 and the revamp of the UI (both the JupyterLab extension, and the app), widgets can be switched from one type to another (e.g. from a pivot table to a chart or reciprocally) very easily.
It allowed us to drop the widget type selection screen and always start directly from a pivot table which is most likely what you want to "test or see the result of a measure you've just coded".

> then you have to go into the left bar and find back the measures and relevant levels you just typed in your cell

In [0.4.3](https://docs.atoti.io/0.5.1/releases/0.4.3.html#added), we introduced a _Convert to atoti Widget Below_ context menu to DataFrames returned by `session.query_mdx()` and `cube.query()` to start an interactive exploration from the same MDX query. It fixed the issue by providing a fast path from a `cube.query()` to an interactive widget. We had to drop this feature in 0.5.0 but we plan to bring it back.
