### ISSUE TITLE
Error when configuring LDAP security

### ISSUE THREAD

**Issue by sjmg** [atoti/atoti#545]
Hello,

We are using atoti+ 0.6.4 with python 3.10 and we have a problem trying to connect with ldap authentication

this is our configuration 

`"authentication": {
                "ldap": {
                    "url": "...",
                    "base_dn": "...",
                    "user_search_base": "...",
                    "group_search_base": "..",
                }
            }`

We attatched the error
[server.log](https://github.com/atoti/atoti/files/8381070/server.log)

We don't understand how to config LDAP security and how to fix this problem.

Could you tell us,what is our problem?

Thanks so much

Regards

**Comment by tibdex** [comment]
Hi, could you check running this example on your side and see if you can log into the session using `euler` as the username and `password` as the password?

```py
session = tt.create_session(
    config={
        "authentication": {
            "ldap": {
                # Connects to a public LDAP service
                "url": "ldap://ldap.forumsys.com:389",
                "base_dn": "dc=example,dc=com",
                "user_search_filter": "(uid={0})",
                "group_search_filter": "(uniqueMember={0})",
            }
        }
    }
)
session.security.individual_roles["euler"] = ["ROLE_USER"]
```

**Comment by tibdex** [comment]
The roles can be specified through one of these ways:
- [individual roles](https://docs.atoti.io/0.6.5/lib/atoti-plus/atoti_plus.security.html#atoti_plus.security.IndividualRoles)
- [LDAP role mapping](https://docs.atoti.io/0.6.5/lib/atoti-plus/atoti_plus.security.html#atoti_plus.security.LdapSecurity.role_mapping) where roles provided by the LDAP server can be mapped to atoti roles.
- [LDAP default roles](https://docs.atoti.io/latest/lib/atoti-plus/atoti_plus.security.html#atoti_plus.security.LdapSecurity.default_roles) which are granted to users loging in through LDAP with no individual roles and no mapped roles.

For everything to work correctly (e.g. for the UI to get the expected roles), these roles must be configured before the user logs in so it wouldn't be possible to ask them to an external service when or after the user logs in.

Could you configure your LDAP server so that it sends some roles that you could map to atoti roles?

**Comment by sjmg** [comment]
Hello,

We continue working with LDAP security but we have a question.

Using ActiveUI with activePivot, we have a screen for write login and pass.

But using UI integrated in Atoti, we don't have this screen, we have a prompt.

It's possible to enable this screen?

Thanks so much
