### ISSUE TITLE
Index out of bound exception during simulation via the UI

### ISSUE THREAD

**Issue by jbe456** [atoti/atoti#70]
## Steps to reproduce

Reported by a user:

Initially, when using a measure simulation and plotting in in a chart, I get the following screen. I’ve set the chart to update in real time.
![image](https://user-images.githubusercontent.com/4415696/84950928-ef7f6f80-b0ef-11ea-8f84-374ebd83962e.png)

I’ve also set a custom measure (which I believe is the source of the issue as I cannot reproduce it without a custom measure)
![image](https://user-images.githubusercontent.com/4415696/84950947-f5755080-b0ef-11ea-9dac-1bed03963464.png)

When I change the measure from 10 to 100, I get
![image](https://user-images.githubusercontent.com/4415696/84950963-fa3a0480-b0ef-11ea-8a45-938e7d6776ff.png)

Changing it from real time to periodic gives the correct chart
![image](https://user-images.githubusercontent.com/4415696/84950973-00c87c00-b0f0-11ea-8b65-fda1d1d71488.png)

## Environment

- atoti: 0.4.0

**Comment by rcolle** [comment]
Can you upload the server logs?
Thanks!

**Comment by jbe456** [comment]
>Can you upload the server logs?

I've only forwarded the info the initial user gave me during a usability review. Haven't tried to reproduce it.

**Comment by Skyscimitar** [comment]
This will be fixed in the next release when the new measure simulation widget will be released.
For info: the reason this happened was because in the old widget, when changing a line we performed two datastore actions (delete, then insert), which meant that the store was temporarily empty. The new widgets perform update actions which means this is no longer a problem.
